### ISSUE TITLE
Damage falloff max and min

### ISSUE THREAD

**Issue by DarkmanBree** [WeaponMechanics/MechanicsMain#100]
### Description

So basically, right now with damage falloff if a bullet goes a set amount of blocks away, the damage drops immediately.

My request: a maximum and a minimum range for falloff.

So say we have an AK-47 that deals 10 damage up close and falls off to 5 damage at range.
Now we have our maximum and minimum damage falloff ranges: 20 blocks and 40 blocks.

- If a bullet hits an enemy that is at 20 blocks or closer, it should still deal the full 10 damage.
- If a bullet hits an enemy that is at 40 blocks or further, it should deal the minimum 5 damage.
- Now if a bullet hits an enemy that is between the max and min range, say 30 blocks, it should deal 7.5 damage.

### Configuration

```yaml
    Dropoff:
    - <travel distance max>~<travel distance min>~<damage amount>
```

**Comment by CJCrafter** [comment]
I want to keep the config for this simple, so I am adding an option in the main `config.yml` which simply makes ALL weapon damage dropoff "smooth". 
```yaml
# If set to true, the damage dropoff will change uniformly with distance.
# See https://github.com/WeaponMechanics/MechanicsMain/issues/100 for more
# information. 
Smooth_Damage_Dropoff: false
```
https://github.com/WeaponMechanics/MechanicsMain/wiki/Damage#dropoff-string-list

Imagine this config
```yaml
    Dropoff:
    - 10 -2
    - 20 -4
    - 30 -6
```
When `Smooth_Damage_Dropoff: true`, If the projectile travels for exactly 10 blocks, it will still deal 2 less damage. However, 
if the projectile traveled 5 blocks, it will do 1 less damage. 
* 25 blocks = 5 less damage. 
* 15 blocks = 3 less damage
* 2.5 blocks = 0.5 less damage

Or if you prefer an image:
![image](https://user-images.githubusercontent.com/43940682/187590084-e26a6eb1-f947-4613-812b-4aba6e76c2c4.png)
