### ISSUE TITLE
Formula for calculating scope (2x, 3x, 10x...) 

### ISSUE THREAD

**Issue by MelonHell** [WeaponMechanics/MechanicsMain#103]
### Description

```java
    public static float getScopeAlt(double level) {
        if (level < 1 || level > 10) {
            debug.log(LogLevel.ERROR,
                    "Tried to get scope level of " + level + ", but only levels between 1 and 10 are allowed.",
                    new IllegalArgumentException("Tried to get scope level of " + level + ", but only levels between 1 and 10 are allowed."));
            return 0;
        }
        return (float) (1.0 / (20 / level - 10)); // checking for division by zero is not needed here, Java gives Infinity when dividing by zero. ABILITIES packet correctly understands the meaning of Infinity
    }
```

setZoom takes values from 1 to 10. maximum zoom in minecraft is 10x (-0.125 value)

**Comment by DeeCaaD** [comment]
Ouch, I should have googled this better before. Since this allows using `double` it would support any FOV change between 1 and 10. Luckily WM is still in BETA so I can make that change to code, thanks!

**Comment by MelonHell** [comment]
> Ouch, I should have googled this better before. Since this allows using `double` it would support any FOV change between 1 and 10. Luckily WM is still in BETA so I can make that change to code, thanks!

I derived this formula myself for my plugin, I'm glad that it will help the plugin

**Comment by MelonHell** [comment]
I think then it’s still worth replacing Increase_Zoom_Per_Stack with an array of values, it will be much more convenient

**Comment by DeeCaaD** [comment]
https://github.com/WeaponMechanics/MechanicsMain/pull/104
