### ISSUE TITLE
More events

### ISSUE THREAD

**Issue by RollexGrief** [WeaponMechanics/MechanicsMain#105]
### Description

String getSelectiveFireState()
String getReloadSymbol()
String getFirearmStateSymbol()
String getAmmoType()
Int getAmmoLeft()
Int getAmmoAvailable()

### Configuration

```
```

**Comment by DeeCaaD** [comment]
Assuming those to [WeaponMechanicsAPI](https://github.com/WeaponMechanics/MechanicsMain/blob/master/WeaponMechanics/src/main/java/me/deecaad/weaponmechanics/WeaponMechanicsAPI.java) class

**Comment by CJCrafter** [comment]
Use [CustomTag](https://github.com/WeaponMechanics/MechanicsMain/blob/master/WeaponMechanics/src/main/java/me/deecaad/weaponmechanics/utils/CustomTag.java)
