### ISSUE TITLE
EntityEquipmentEvent

### ISSUE THREAD

**Issue by DeeCaaD** [WeaponMechanics/MechanicsMain#11]
The `EntityEquipmentEvent` is an ongoing project to be able to detect all changes to an `EntityEquipment`. It works best for non-stackable items (tools/weapons), but should work for all items.

Current Known Issues:
* Doesn't work at all in versions <1.11
* Sometimes items appear to disappear
* Behavior of event changes depending on player gamemode
* Placing blocks in survival mode seems to cause issues

**Comment by CJCrafter** [comment]
Added high priority since the event can *sometimes* clear the held item.

**Comment by CJCrafter** [comment]
>Sometimes items appear to disappear
Behavior of event changes depending on player gamemode
Placing blocks in survival mode seems to cause issues

Probably fixed in e85d85a and 8d03ad2

**Comment by CJCrafter** [comment]
Issue is still present. 

To replicate:
1. More your cursor to first (empty) hotbar slot
2. `/wm get <any weapon>`
3. While the weapon is supposed to appear at your currently selected slot, it does not.
