### ISSUE TITLE
Weapon_Equip_Delay bypass

### ISSUE THREAD

**Issue by 3Lord3** [WeaponMechanics/MechanicsMain#112]
### Has this issue already been reported? Did you ask for help before making this report?

- [X] I have searched the existing issues
- [x] I have asked for help

### Current Behavior

If you start firing fast enough when switching to a weapon, you can bypass its Weapon_Equip_Delay

### Expected Behavior

Weapon_Equip_Delay always works

### Steps To Reproduce

1. Take any weapon with Weapon_Equip_Delay
2. Switch from any slot to this weapon and immediately press the firing button

### Frequency

You need to start shooting at a certain short moment, it does not always work out

### Version and Log

[2022-05-19-1.log.gz](https://github.com/WeaponMechanics/MechanicsMain/files/8737611/2022-05-19-1.log.gz)
![image](https://user-images.githubusercontent.com/62335161/169483339-c62db152-97ec-4fa8-b3ba-2ae82915716c.png)

### Anything else?

https://user-images.githubusercontent.com/62335161/169483449-48ca58cc-20dd-4d0f-b38e-be84f2184676.mp4

**Comment by DeeCaaD** [comment]
You probably know better CJCrafter. I don't dare to just remove that runnable unless I know why its there

https://github.com/WeaponMechanics/MechanicsMain/blob/master/MechanicsCore/src/main/java/me/deecaad/core/events/triggers/EquipListener.java#L83
