### ISSUE TITLE
Should more event when shooting

### ISSUE THREAD

**Issue by Ruomoe** [WeaponMechanics/MechanicsMain#114]
### Description

I'm coding WeaponMechanics's gun attachments plugin, but i want to change the gun to having more features for shoot.
Now i just can only change features like 'Damage', 'Reload Ammo Amount' of the gun, and 'Reload Time'.
i want change 'Recoil', 'Movement', 'Spread', could you please add the events.
If you will accept my code, i can commit pull requests.

### Configuration

Dont need config.

**Comment by CJCrafter** [comment]
The API is a WIP

**Comment by CJCrafter** [comment]
You can always make a Pull Request, but this is a project DeeCaaD will be working on shortly

**Comment by Ruomoe** [comment]
Thanks
