### ISSUE TITLE
Problems in friendlyFire

### ISSUE THREAD

**Issue by Xiaye2332** [WeaponMechanics/MechanicsMain#116]
### Has this issue already been reported? Did you ask for help before making this report?

- [X] I have searched the existing issues
- [X] I have asked for help

### Current Behavior

I used command `/team modify ct friendlyFire false` to disable friendlyFire in team <ct>, but other team can not attack them after I use this. But it is fine in plugin CrackShot. 

### Expected Behavior

team CT can only do damage to team T and tean T can only do damage to team CT.

### Steps To Reproduce

1.Create a team by `/team create xx`
2.Disable friendlyFire by '/team modify xx friendlyFire false'
3.at this time, noone can attack players in team xx anymore.

### Frequency

100% definitely

### Version and Log

[12:10:11 INFO]: WeaponMechanics, v1.7.1-BETA
[12:10:11 INFO]:   ➢ Authors: DeeCaaD, CJCrafter
[12:10:11 INFO]:   ➢ Command: /weaponmechanics
[12:10:11 INFO]:   ➢ Server: Paper git-Paper-411 (MC: 1.17.1)
[12:10:11 INFO]:   ➢ MechanicsCore: 1.2.2-BETA
[12:10:11 INFO]:   ➢ Java: 16.0.2
[12:10:11 INFO]:   ➢ Supported plugins: WorldEdit, PlaceholderAPI

![UPB34 2MJ1X5NAWQS7} G{A](https://user-images.githubusercontent.com/86192453/171982033-df610812-39b9-4c4f-989d-6f58c4a83f90.png)

**Comment by CJCrafter** [comment]
Interesting issue... we have code to handle teams, which looks fine... I wonder if the bukkit api for teams is out of date? 
https://github.com/WeaponMechanics/MechanicsMain/blob/646e10c11ee8c92d030aa55252805b5fcae2114c/WeaponMechanics/src/main/java/me/deecaad/weaponmechanics/weapon/damage/DamageUtil.java#L223-L250

**Comment by DeeCaaD** [comment]
https://github.com/WeaponMechanics/MechanicsMain/commit/5bfd46c4a2fb56ba407bcea551245d6d376ffbb3
