### ISSUE TITLE
ADS Delay

### ISSUE THREAD

**Issue by outofthetime** [WeaponMechanics/MechanicsMain#120]
### Description

ADS Delay is basically the amount of time it takes to aim down sight for a certain gun. If you look in a game, like COD (Modern Warfare 2019 as a good example), you see that some guns take a longer or shorter time to ADS because of their weight, whether they are lighter or heavier.

### Configuration

Scope:
  Scope_Delay: <integer / ticks>

**Comment by CJCrafter** [comment]
Completely overlooked feature...

**Comment by outofthetime** [comment]
this would be pretty cool in the plugin

**Comment by CJCrafter** [comment]
No idea when it was added, but here: https://github.com/WeaponMechanics/MechanicsMain/wiki/Scoping#shoot_delay_after_scope-integer
