### ISSUE TITLE
about head hitbox

### ISSUE THREAD

**Issue by TeQTabanca** [WeaponMechanics/MechanicsMain#121]
### Has this issue already been reported? Did you ask for help before making this report?

- [X] I have searched the existing issues
- [X] I have asked for help

### Current Behavior

**When I hit the heads of the entities, sometimes the head hits, sometimes the body counts and sometimes it doesn't count at all. It looks like it needs reconsideration.**

### Expected Behavior

**When I hit the heads of entities, it should count heads directly.**

### Steps To Reproduce

- I point it at the heads of entities.
- I shoot last.

### Frequency

%100

### Version and Log

![image](https://user-images.githubusercontent.com/89253304/174904983-9cba4d1b-c659-442c-8cce-7d8a038aff0e.png)

### Anything else?

**By the way, the monster I tested is HUSK. Even though I made the HUSK monster's hitbox equal, if I hit the throat side, the head counts.**

### ([Video](https://s5.dosya.tc/en2.php?a=server7/nm743m/weaponmechanics_head_hitbox_problem.mp4&b=e75ecf49a181ef5c5bfd3ece08d4372f))

  HUSK:
    Horizontal_Entity: false
    HEAD: 0.25
    BODY: 0.25
    ARMS: true
    LEGS: 0.25
    FEET: 0.25

**Comment by DeeCaaD** [comment]
Some entities hitboxes just are like that

![2022-06-22_01 32 36](https://user-images.githubusercontent.com/18332343/174907993-3e589824-d67a-46cd-9c68-9a5fe6f56ecc.png)

**Comment by DeeCaaD** [comment]
https://github.com/WeaponMechanics/MechanicsMain/commit/40d3ec52b1081a2a63c142fc9cf0d0dbcc2a74ba
