### ISSUE TITLE
Ability to change how a melee weapon is triggered

### ISSUE THREAD

**Issue by galacticwarrior9** [WeaponMechanics/MechanicsMain#129]
### Description

Right now, melee weapons can only be triggered by left-clicking. This causes problems when these weapons are used as attachments on guns which themselves are triggered when left-clicked. 

Proposal: adding the ability to specify how a melee weapon can be triggered, and to have this also work for weapons which specify the melee weapon as a `Melee_Attachment`

### Configuration

Using the existing configuration for setting a trigger serializer. The proposal is to make it also work for melee weapons:

```yaml
  Shoot:
    Trigger: <TriggerSerializer>
```

**Comment by CJCrafter** [comment]
Don't use left click for shooting.
