### ISSUE TITLE
Consume Item When Empty

### ISSUE THREAD

**Issue by Herobrine15432** [WeaponMechanics/MechanicsMain#136]
### Description

A good idea is to do weapon like "Consume_Item_On_Shoot" but giving more than 1 ammo to the gun and blocking the possibility of reloading it
So a weapon that can have more of 1 shoot but that can't be reloaded and that when is empty is consumed

### Configuration

Reload:
  Magazine_Size: <amount>
  Consume_Item_When_Empty: 
    enabled: <true/false> #if true, the weapon can't be reloaded and the item will be removed when empty
    Mechanics: <MechanicsSerializer> #Mechanics to do when the item will be removed from inventory

**Comment by CJCrafter** [comment]
Already added
