### ISSUE TITLE
SoundMechanic compatibility issue + bug

### ISSUE THREAD

**Issue by DeeCaaD** [WeaponMechanics/MechanicsMain#157]
### Has this issue already been reported? Did you ask for help before making this report?

- [X] I have searched the existing issues
- [X] I have asked for help

### Current Behavior

1) getNearbyEntitities predicate causes compatibility issue with older servers because predicate didn't exist (`DistanceUtil(World world, double distance)` method can be added): https://github.com/WeaponMechanics/MechanicsMain/blob/master/WeaponMechanics/src/main/java/me/deecaad/weaponmechanics/mechanics/defaultmechanics/SoundMechanic.java#L266

2) Sound `distance` doesn't work. Even when defined using `distance` (+ or when its converted from `volume` [here](https://github.com/WeaponMechanics/MechanicsMain/blob/master/WeaponMechanics/src/main/java/me/deecaad/weaponmechanics/mechanics/defaultmechanics/SoundMechanic.java#L216)). I were only able to hear the sound within 16 radius.

In fact there is other improvement also to `distance`. With MC own sounds according to [protocol](https://wiki.vg/Protocol#Sound_Effect)
<html><body>

Volume | Float | 1.0 is 100%, capped between 0.0 and 1.0 by Notchian clients.
-- | -- | --

</body>
</html>
And with custom sounds
<html><body>

Volume | Float | 1 is 100%, can be more.
-- | -- | --

</body>
</html>

Meaning when `distance` is used, the `volume` should lerp between like `1.0 - 0.1 (100% - 10% volume)` based on the distance.

### Expected Behavior

You can hear sound from further than 16 blocks

### Steps To Reproduce

Easiest to test using `Semtex`
1) `/wm get Semtex`
2) Throw
3) You can only hear the EXPLOSION within 16 blocks even when default config has volume set to `6` -> `6 * 16 = 96 blocks`

### Frequency

100%

### Version and Log

Tested in 1.19 with WM `1.9.10`

**Comment by CJCrafter** [comment]
In 1.19, we have sound attenuation which makes this feature much more possible! However in older versions, we have to increase the volume of sounds to allow players to hear them.

Alternatively, we could normalize the sound's location relative to the player and multiply it by 8, for example. This may have unintended side effects... The sound may actually "feel closer" due to how 3d sound is implemented in Minecraft. A proper solution requires much more testing

**Comment by CJCrafter** [comment]
People have to use high volume sounds or turn off sound attenuation in their resource pack. Nothing we can do from the plugin's end.
