### ISSUE TITLE
ArmorStand projectile doesn't disappeard if a block is targeted

### ISSUE THREAD

**Issue by Herobrine15432** [WeaponMechanics/MechanicsMain#160]
### Has this issue already been reported? Did you ask for help before making this report?

- [X] I have searched the existing issues
- [X] I have asked for help

### Current Behavior

There is a bug with armor stand projectileWhen I shoot with a weapon having a block targeted, the armorstand still remain 
![Immagine 2022-09-11 223002](https://user-images.githubusercontent.com/79306926/189547714-eb945a71-62d0-4255-8694-c79935281922.png)

### Expected Behavior

The armorstand should be removed

### Steps To Reproduce

This is the config:

anubis_eye:
    Info:
      Weapon_Item:
        Type: CLOCK
        Custom_Model_Data: 10001
        Name: '&eOcchio di Anubis'
        Lore:
          - '&7Un arma proveniente dalla'
          - '&7mitologia egizia'
          - '&c'
          - '&8[&bRarità&8] &d&lLEGGENDARIA'
        Unbreakable: true
        Hide_Flags: true
      Weapon_Info_Display:
        Action_Bar:
          Message: '&6Occhio di Anubis%firearm-state% &7«&6%ammo-left%&7»&6%reload%'
      Weapon_Get_Mechanics:
        Sounds:
          - ITEM_ARMOR_EQUIP_CHAIN-1-0.75
      Weapon_Equip_Delay: 30
      Show_Cooldown:
        Weapon_Equip_Delay: true
        Reload_Time: true
      Cancel:
        Drop_Item: true
        Swap_Hands: true
        Arm_Swing_Animation: true
    Projectile:
      Projectile_Settings:
        Type: ARMOR_STAND
        Projectile_Item_Or_Block:
          Type: INK_SAC
          Custom_Model_Data: 10000
        Gravity: 0.05
        Minimum:
          Speed: 60
        Drag:
          Base: 0.99
          In_Water: 0.96
          When_Raining_Or_Snowing: 0.98
        Maximum_Alive_Ticks: 600
        Maximum_Travel_Distance: 500
      Through:
        Maximum_Through_Amount: 0
        Blocks:
          Default_Speed_Multiplier: 0.8
          Whitelist: true
          List:
            - "$GLASS"
            - "$FENCE"
        Entities:
          Allow_Any: true
          Default_Speed_Multiplier: 0.7
    Shoot:
      Trigger:
        Main_Hand: RIGHT_CLICK
        Off_Hand: RIGHT_CLICK
      Projectile_Speed: 100
      #Fully_Automatic_Shots_Per_Second: 10
      Delay_Between_Shots: 20
      Spread:
        Base_Spread: 1
        Modify_Spread_When:
          Zooming: 50%
          Sneaking: 50%
          In_Midair: 150%
      Recoil:
        Push_Time: 300
        Horizontal:
        - 4.2
        - -3.8
        - -4.6
        Vertical:
        - 8
        - 9.6
        - 10.1
        Modify_Recoil_When:
          Zooming: 50%
          Sneaking: 50%
          In_Midair: 150%
      Mechanics:
        Sounds:
        - 'custom:shoot.occhio_anubis-6-1-0-0.1'
        Movement:
          Movement_Speed: -10
    Reload:
      Trigger:
        Main_Hand: DROP_ITEM
        Off_Hand: DROP_ITEM
      Magazine_Size: 10
      Reload_Duration: 180
      Start_Mechanics:
        Sounds:
          - 'custom:reload.start.normal-0.5-1-0-0.1'
      Finish_Mechanics:
        Sounds:
          - 'custom:reload.end.normal-0.5-1-0-0.1'
    Damage:
      Base_Damage: 8.6
      Armor_Damage: 10
      Enable_Friendly_Fire: false
      Enable_Owner_Immunity: false
      Dropoff:
      - 20~-4
      - 50~-6
      - 70~-7
        
    Scope:
      Trigger:
        Main_Hand: LEFT_CLICK
        Off_Hand: LEFT_CLICK
      Zoom_Amount: 4
      Mechanics:
        Sounds:
          - 'custom:scope.in-0.5-1-0-0.1'
      Zoom_Off:
        Mechanics:
          Sounds:
            - 'custom:scope.out-0.5-1-0-0.1'
          
        
    Firearm_Action:
      Type: SLIDE
      Open:
        Time: 8
        Mechanics:
          Sounds:
            - BLOCK_NOTE_BLOCK_HAT-0.5-1-0-0.1
            - BLOCK_PISTON_CONTRACT-0.5-1-2-0.1
      Close:
        Time: 8
        Mechanics:
          Sounds:
            - BLOCK_PISTON_EXTEND-0.5-1-0-0.1

2) shoot for example looking the floor

3) the armorstand will remain

### Frequency

100%

### Version and Log

![image](https://user-images.githubusercontent.com/79306926/189547786-801bf07f-d1a8-42c5-a5ba-f6d269cb8d33.png)
[latest.log](https://github.com/WeaponMechanics/MechanicsMain/files/9543487/latest.log)

(THE ERRORS IN THE LOG ARE OF ANOTHER BUG, THIS BUG DOESN'T SEND ERRORS

**Comment by DeeCaaD** [comment]
https://github.com/WeaponMechanics/MechanicsMain/commit/3176aa753c289c2711d34ad579dbd657adc165c2
