### ISSUE TITLE
Made chests broken by explosions drop items if Regen is off

### ISSUE THREAD

**Issue by Herobrine15432** [WeaponMechanics/MechanicsMain#161]
### Description

A way to made blocks with inventory drops items if they are broken by explosions and if the block regeneration is disabled

### Configuration

Explosion:
  Block_Damage:
    Containers_Drops: true

**Comment by CJCrafter** [comment]
fixed in [4dae761](https://github.com/WeaponMechanics/MechanicsMain/commit/4dae761c04df8682e8e0cde42a3e36f45b7c75ef)

**Comment by CJCrafter** [comment]
Still an issue... Seems that there were some undocumented spigot api changes in 1.19... More testing required

**Comment by CJCrafter** [comment]
fixed in 552683c4c7ae1e965717ba558da507b03c08b08f
