### ISSUE TITLE
Change visual item in hotbar after swapping away from scope.

### ISSUE THREAD

**Issue by Kleypex** [WeaponMechanics/MechanicsMain#166]
### Description

Hello,

I have models where the scope is seperated completly and run a different cusotom model data.
This means I use the same model/scope for different weapons. 

If I hold a weapon, scope in (model is now changed to scope), then change to different id in hotbar. 1,2,3,4 whatever.
Then the gun remains on the scope model until the player goes back over it. 
Would be nice that if you scope in, change hotbar or whatever. Then the gun changes back to it's original state.

It's a visual thing. But would be nice to have.
Thanks.

### Configuration

Not needed

**Comment by DeeCaaD** [comment]
Hmm, but it doesn't even have any visible change anywhere? Like it looks the same in the inventory still even if its scope model

**Comment by Kleypex** [comment]
It does have a visual change when it's two different models.
I don't just change the first person view with that specific gun to line up the scope that is currently on.
I change the it to a different item. 
![image](https://user-images.githubusercontent.com/111271933/191505539-d0b9cd75-47d9-4990-9bf1-51be3c3d359d.png)
Image is showing scoped in with a gun. If I swop away from it, then it stay as a scope in my hotbar. It doesn't change back to unscoped weapon.

**Comment by Kleypex** [comment]
![image](https://user-images.githubusercontent.com/111271933/191505906-363c4989-cf3b-4e30-b83d-42e74dfc475b.png)

**Comment by CJCrafter** [comment]
Possible fix: apply skin onDequip using `EntityEquipmentEvent`

**Comment by Kleypex** [comment]
> Possible fix: apply skin onDequip using `EntityEquipmentEvent`

Was this added in 1.11.10?

**Comment by DeeCaaD** [comment]
No, these are closed as soon as they get completed

**Comment by Kleypex** [comment]
not completed
