### ISSUE TITLE
Recoil recovery speed is pushing too low from where I fired.

### ISSUE THREAD

**Issue by DarkmanBree** [WeaponMechanics/MechanicsMain#171]
### Has this issue already been reported? Did you ask for help before making this report?

- [X] I have searched the existing issues
- [X] I have asked for help

### Current Behavior

When firing, I have a 100 millisecond smooth push recoil that goes up and diagonal, and then 250 (increased to 500 for testing) milliseconds of recovery speed, the recovery speed stops lower than where I shot the gun at, the higher the number, the lower it goes.

### Expected Behavior

I expect recoil recovery to end where I initially shot the gun, with recovery time being the time it takes to recover to that point.

### Steps To Reproduce

![image](https://user-images.githubusercontent.com/29287160/194153421-1ca4a214-6dca-416f-87f2-127dd9d70625.png)

Then shoot the weapon, with this the recoil recovery is ending lower than where I shot my gun at.

### Frequency

Happens 100% of the time.

### Version and Log

![image](https://user-images.githubusercontent.com/29287160/194154108-a24abdc8-e2dc-40cd-99bf-8fa63315e68d.png)
[latest.log](https://github.com/WeaponMechanics/MechanicsMain/files/9718710/latest.log)

**Comment by DeeCaaD** [comment]
https://github.com/WeaponMechanics/MechanicsMain/commit/66bfd3b6d397c5bebed2c80ed721575e6268fbef
