### ISSUE TITLE
Creative Mode bypasses ammo requirement

### ISSUE THREAD

**Issue by DarkmanBree** [WeaponMechanics/MechanicsMain#176]
### Description

If you have a weapon that requires ammo to reload/shoot, being in Creative Mode should bypass that.
This is so you don't have to keep spawning in more ammo when testing a gun in Creative Mode, it's quite annoying.

### Configuration

No configuration needed.

### Payment (optional)

- [ ] I'm willing to pay for this feature

**Comment by DeeCaaD** [comment]
Configuration -> option in config.yml for this bypass (defaults to false). This because otherwise people would be confused of why ammo isn't working

**Comment by DarkmanBree** [comment]
Can work too.
