### ISSUE TITLE
giveammo command

### ISSUE THREAD

**Issue by darktubeNL** [WeaponMechanics/MechanicsMain#182]
### Description

a command to give a player ammo

### Configuration

/weaponmechanics giveammo (player) (gun) 

### Payment (optional)

- [ ] I'm willing to pay for this feature

**Comment by CJCrafter** [comment]
This is **not** the same as `/wm ammo`, which gives the player who used the command ammo for the gun they are holding. This `/wm giveammo` would be helpful for map makers
