### ISSUE TITLE
Knockback Multiplier

### ISSUE THREAD

**Issue by supxnova** [WeaponMechanics/MechanicsMain#184]
### Description

I want the explosions to give the option for knockback multiplier.
Crackshot did this so exactly how they did it works perfectly fine

### Configuration

rocket_launcher:
  Projectile:
    Projectile_Settings:
      Type: "FIREBALL"
      Projectile_Item_Or_Block:
        Type: "FEATHER"
        Custom_Model_Data: 1
      Minimum:
        Speed: 40
      Gravity: 0.02
      Drag:
        Base: 0.99
        In_Water: 0.96
        When_Raining_Or_Snowing: 0.98
      Size: 0.5
      KnockbackMultiplier: 2 #0 for no knockback. 1 for regular and 2 for 2 times the knockback etc.

### Payment (optional)

- [ ] I'm willing to pay for this feature

**Comment by CJCrafter** [comment]
This should replace the `Use_Vanilla_Knockback: <true/false>` toggle

**Comment by supxnova** [comment]
Could some documentation be written about this please

**Comment by Scot-Survivor** [comment]
What commits were referencing this issue?
