### ISSUE TITLE
Option to force unscope after shooting.

### ISSUE THREAD

**Issue by DarkmanBree** [WeaponMechanics/MechanicsMain#187]
### Description

Simply an option to automatically unscope your gun after you shoot your gun.
Useful to keep bolt action snipers unique from semi automatic snipers.

The integer is a number in ticks, 10 means you will unscope your gun 0.5 seconds after shooting the gun.
Leave this at empty or 0 to disable this feature.

### Configuration

```yaml
Scope:
  Unscope_After_Shot: <integer>
```

### Payment (optional)

- [ ] I'm willing to pay for this feature

**Comment by CJCrafter** [comment]
duplicate #73
