### ISSUE TITLE
Friendly fire

### ISSUE THREAD

**Issue by DarkmanBree** [WeaponMechanics/MechanicsMain#191]
### Description

Another feature from CrackShot, however I would like to take it out of explosions and just include it as a general damage feature.

Self explanatory, when this is enabled, your bullets can deal friendly fire damage if a plugin or the vanilla **/team** is used to normally prevent teammates to damage eachother.
This should work with everything from bullets to explosions.

Useful for either trolling, or creating a buff like custom explosions that heal teammates or a literal TF2 Medigun that heals when you shoot your team.

### Configuration

```yaml
Damage:
  Enable_Friendly_Fire: <true/false>
```

### Payment (optional)

- [ ] I'm willing to pay for this feature

**Comment by CJCrafter** [comment]
You can disable friendly fire through the `/team` command, WeaponMechanics automatically reads that when damaging players

**Comment by CJCrafter** [comment]
Add option

```yaml
    Ignore_Teams: <true/false> 
```
to damage

**Comment by CJCrafter** [comment]
https://github.com/WeaponMechanics/MechanicsMain/wiki/Damage#ignore_teams-truefalse
