### ISSUE TITLE
ProjectileHitEntityEvent add getDamage()

### ISSUE THREAD

**Issue by EmSockz** [WeaponMechanics/MechanicsMain#196]
### Description

add a method for receiving the damage (getDamage()) that was dealt to the entity in the event ProjectileHitEntityEvent

### Configuration

missing

### Payment (optional)

- [ ] I'm willing to pay for this feature

**Comment by CJCrafter** [comment]
https://github.com/WeaponMechanics/MechanicsMain/blob/master/WeaponMechanics/src/main/java/me/deecaad/weaponmechanics/weapon/weaponevents/WeaponDamageEntityEvent.java#L87
