### ISSUE TITLE
Destroy gun when empty feature

### ISSUE THREAD

**Issue by DarkmanBree** [WeaponMechanics/MechanicsMain#197]
### Description

Missing CrackShot feature.

When true, when the gun magazine runs out of ammo (0 ammo left), the gun will be deleted.
Useful for limited use guns that last until their magazine runs out.

### Configuration

```yaml
Reload:
  Destroy_When_Empty: <true/false>
```

### Payment (optional)

- [ ] I'm willing to pay for this feature

**Comment by CJCrafter** [comment]
https://github.com/WeaponMechanics/MechanicsMain/wiki/Shooting#destroy_when_empty-truefalse
