### ISSUE TITLE
Custom tags in the NBT

### ISSUE THREAD

**Issue by DarkmanBree** [WeaponMechanics/MechanicsMain#198]
### Description

So this is a way to add a custom tag of choice in the NBT of your weapon item.
This is mainly just for advanced features such as clearing a player's inventory off weapons with that specific tag. (e.g weapons using Diamond Hoe with the custom tag: "Primary")

A command like: `/clear Darkman_Bree diamond_hoe{CustomTag:"Primary"}` would clear all Diamond Hoe's with the "Primary" custom tag in it.

This should be in the Item Serializer

### Configuration

```yaml
Item:
  Custom_Tag: <tag>
```

### Payment (optional)

- [ ] I'm willing to pay for this feature

**Comment by CJCrafter** [comment]
https://github.com/WeaponMechanics/MechanicsMain/wiki/General#tags
