### ISSUE TITLE
Wiki images are not visible

### ISSUE THREAD

**Issue by CJCrafter** [WeaponMechanics/MechanicsMain#20]
### Link to code

https://github.com/WeaponMechanics/MechanicsMain/wiki/Shooting#spread_image, https://github.com/WeaponMechanics/MechanicsMain/wiki/General#message-color-codes, https://github.com/WeaponMechanics/MechanicsMain/wiki/General#recipe

### Improvements

Use these links instead
![colorcodes](https://user-images.githubusercontent.com/43940682/151718277-6fa069cc-3a1a-483e-991d-f9c040071a00.png)
![crafting](https://user-images.githubusercontent.com/43940682/151718278-4619f84c-072c-46dc-958d-6c11db10534c.png)
![gear](https://user-images.githubusercontent.com/43940682/151718279-668a5398-dcf7-4729-9efa-1b1ed3ceff4d.png)

**Comment by DeeCaaD** [comment]
![Logo 96x96](https://user-images.githubusercontent.com/18332343/153458196-c4e219ab-01b5-46dc-a3f6-0976a2d18938.png)
![Logo 512x512](https://user-images.githubusercontent.com/18332343/153458201-359010d9-a173-42e7-aa4d-7e2d7db939c1.png)

**Comment by DeeCaaD** [comment]
![Logo 256x256](https://user-images.githubusercontent.com/18332343/153458593-0adbbb54-3ccd-4edd-9251-ed81b841ce90.png)

**Comment by CJCrafter** [comment]
![image](https://user-images.githubusercontent.com/43940682/181638380-921e157d-15d2-46ab-abe6-189ce1795b9b.png)

**Comment by CJCrafter** [comment]
![image](https://user-images.githubusercontent.com/43940682/181919499-91ec8804-95e7-4dfb-847b-6e2ba3ae1bd6.png)

**Comment by CJCrafter** [comment]
![pearl](https://user-images.githubusercontent.com/43940682/182694676-26306d42-7015-4b96-83fc-04dc46c11668.png)

**Comment by CJCrafter** [comment]
![image](https://user-images.githubusercontent.com/43940682/184519185-6b1576b2-2055-4c64-a98d-c0544b56df1b.png)

**Comment by DeeCaaD** [comment]
![WeaponMechanicsBanner3](https://user-images.githubusercontent.com/18332343/188478631-ecccb1a6-51aa-4f9c-bfa6-de666c2658d9.png)

**Comment by CJCrafter** [comment]
![2022-09-08_03 13 32](https://user-images.githubusercontent.com/43940682/189499803-30112616-40c9-4159-85d2-375dbe3d2a7f.png)

**Comment by CJCrafter** [comment]
![image](https://user-images.githubusercontent.com/43940682/189500046-a860de84-f54e-4975-a6d0-406a310cc133.png)

**Comment by CJCrafter** [comment]
![reticle](https://user-images.githubusercontent.com/43940682/189747433-f1c82f3e-c757-47c7-9845-121146f15db8.png)

**Comment by CJCrafter** [comment]
![crafting_output](https://user-images.githubusercontent.com/43940682/190881222-e6df9d5c-2934-4494-b8b5-93032097e52a.png)

**Comment by CJCrafter** [comment]
![WeaponMechanicsSignShopBanner](https://user-images.githubusercontent.com/43940682/191133612-9c8c2d03-368a-4c65-8393-21e624a70fd9.png)

**Comment by CJCrafter** [comment]
<img width="401" alt="image" src="https://user-images.githubusercontent.com/43940682/192194576-cae0688e-7812-4e0e-b0f0-15ae091934cd.png">

**Comment by CJCrafter** [comment]
![action-bar](https://user-images.githubusercontent.com/43940682/213801725-74be10e5-7954-4b34-9a31-0531dc5c3c9e.png)
![title](https://user-images.githubusercontent.com/43940682/213801728-0fee5c74-17fe-4767-9a0f-68d56fa71c02.png)

for new wiki :)

**Comment by CJCrafter** [comment]
<img width="496" alt="image" src="https://user-images.githubusercontent.com/43940682/218564371-7acb1e05-b5d3-4ce2-87b0-73a98b64e243.png">

**Comment by CJCrafter** [comment]
![get-latest-log](https://user-images.githubusercontent.com/43940682/218565746-d3692524-d652-4276-8e96-8be480d77bfd.gif)

**Comment by CJCrafter** [comment]
![2023-06-30_16 30 40](https://github.com/WeaponMechanics/MechanicsMain/assets/43940682/54f1918f-aeed-4bf1-9cc2-4b2b1a33e7d1)

**Comment by DeeCaaD** [comment]
Love the usage of this "issue" :D

**Comment by CJCrafter** [comment]
Gotta bypass the Spigot upload limit!
