### ISSUE TITLE
Weapons that fire with left-click cannot be fired from close range 

### ISSUE THREAD

**Issue by galacticwarrior9** [WeaponMechanics/MechanicsMain#201]
### Has this issue already been reported? Did you ask for help before making this report?

- [X] I have searched the existing issues
- [X] I have asked for help

### Current Behavior

Non-melee weapons that have a `LEFT_CLICK` shoot trigger will not fire if you are looking at an entity that is less than 6 blocks away from you. Instead, the vanilla 'weak attack' sound plays, as if you are trying to hit it with the gun. 

### Expected Behavior

The weapon will fire even if you are looking at a nearby entity. 

### Steps To Reproduce

1. Use this [config](https://pastebin.com/2Ls6tZVA)
2. Spawn a mob
3. Point the gun at the mob at point blank range and try to fire with left-click
4. Slowly move away from the mob until the gun fires

### Frequency

100% of the time 

### Version and Log

[Log file link](https://github.com/WeaponMechanics/MechanicsMain/files/9942827/log.txt)

![Screenshot](https://i.gyazo.com/df5e8e61db2c1ba55cf3843918389261.png)

### Anything else?

Video demonstration: 
https://user-images.githubusercontent.com/9055352/200096461-b1462329-f572-4356-911e-75bb6c8c1ece.mp4

**Comment by DeeCaaD** [comment]
Requires trigger activation when damaging entity via left-click (TriggerType.LEFT_CLICK -> weapon handler)
