### ISSUE TITLE
Blot problem in Firearms

### ISSUE THREAD

**Issue by XyBv587** [WeaponMechanics/MechanicsMain#202]
### Description

The 'LEVER' Firearms has a problem

Wiki:

When Reloading:
 - If empty
     - Weapon Opens (Ejecting a round, and unlocking the mag)
     - Weapon Reloads
     - Weapon Closes (Loading a round, and blocking the mag)
 - If not empty
     - Weapon Reloads

some old gun like Kar98k , if gun is not empty and player want add ammo to gun
player must open bolt ( lost loaded bullet )
reload ammo
close bolt
shot

if player open the bolt after shoot and reload , he can reload ammo with no bullet lost (because bolt is open)
if bolt is close , player will lose one bullets on he open the bolt (because one bullets will hook and ejection by bolt)

![testgit](https://user-images.githubusercontent.com/38648529/200171051-7699c71d-a0e4-4fe5-8f85-ed60c74db046.png)

* The example "Kar98k.yml" has wrong firearms

### Configuration

Firearm_Action:
    Type: LEVER
    Open:
      Time: <ticks>
      Mechanics: <MechanicsSerializer>
    Close:
      Time: <ticks>
      Mechanics: <MechanicsSerializer>

Firearm_Action:
    Type: BOLT
    Open:
      Time: <ticks>
      Mechanics: <MechanicsSerializer>
    Close:
      Time: <ticks>
      Mechanics: <MechanicsSerializer>

### Payment (optional)

- [ ] I'm willing to pay for this feature

**Comment by DeeCaaD** [comment]
https://github.com/WeaponMechanics/MechanicsMain/issues/189

Will be possible when new firearm action system is implemented
