### ISSUE TITLE
Mechanics. Send sound only to player who triggers Mechanic

### ISSUE THREAD

**Issue by Kleypex** [WeaponMechanics/MechanicsMain#204]
### Description

Option to send Mechanic sound only to the player who is triggering the event.

For instance the Out_Of_Ammo event. Players can just spam Q/Right click to trigger reload. 
If they don't have the ammo on them it will play a sound. Players can just hold this button and it will be annoying to others.

Instead of playing the sound to everyone with volume etc. 0.5. Would be nice if it could be send only to the player who is trying to spam or reload his/her gun.

### Configuration

    Ammo:
      Out_Of_Ammo:
        Message:
          Action_Bar:
            Message: Empty magazine
            Time: 1
        Sounds:
          - 'custom:reload.end.normal-0.5-1-0-0.1'

### Payment (optional)

- [ ] I'm willing to pay for this feature

**Comment by CJCrafter** [comment]
I cheated to use something like this in WMC for bullet "zip" sounds. Maybe we can add another argument at the end to only send the sound to the caster.

**Comment by DarkmanBree** [comment]
I support this, I don't need other players to hear me reload :(

**Comment by CJCrafter** [comment]
Fixed by #244
