### ISSUE TITLE
Option to require skylight for playing sounds

### ISSUE THREAD

**Issue by galacticwarrior9** [WeaponMechanics/MechanicsMain#205]
### Description

Currently 'interior' sounds can be played by filling buildings with `CAVE_AIR`/`VOID_AIR` and configuring the sound to only play if the player's head is inside that material. This is suitable for pre-made maps, but not survival servers where player building is permitted. 

I think an option for sounds to only play above or below a specified [skylight level](https://minecraft.fandom.com/wiki/Light#Sky_light) is the best solution for such servers. Because skylight does not change at night, interior areas will generally have lower skylight values than exterior areas.

### Configuration

I am not sure what the best way to represent this in the configuration would be. The simplest would be to add `<minimum_skylight>` and `<maximum_skylight>` options to the end of sound strings (or maybe just `<maximum_skylight>` for the sake of brevity):

```
custom:<sound> <volume> <pitch> <delay> <pitchNoise> <distance> <material> <category> <minimum skylight> <maximum skylight>
```

### Payment (optional)

- [ ] I'm willing to pay for this feature

**Comment by CJCrafter** [comment]
It's a cool idea... I think I would implement this as an option in config.yml. I don't want to add any more options to the sound section (Maybe until I add inline serializers or something, but we voted against those awhile ago).

```yaml
# If you uncomment the lines, instead of checking for `CAVE_AIR` and `VOID AIR`, we check for skylight level.
Skylight_Sounds:
  #CAVE_AIR: 0-7
  #VOID_AIR: 4-10
```

**Comment by CJCrafter** [comment]
https://github.com/WeaponMechanics/MechanicsMain/wiki/LightLevelCondition
