### ISSUE TITLE
ItemsAdder's blocks support and problem fix

### ISSUE THREAD

**Issue by Herobrine15432** [WeaponMechanics/MechanicsMain#210]
### Description

- [ ]  If it is possible I'd like that servers that use ItemsAdder can enable an "ItemAdder_Compatibility" in WM's config to allow to prevent duplication of block on BlockDamage and the support of "Fall_Block_Spawn" of these block (PROBLEM LINKED WITH A VIDEO)

- [ ] Another point of my request is add the possibility to use ItemsAdder's block as projectile in "Falling Block"

_I'm asking this also because I think it should't be only a my problem because ItemsAdder is used in about 2000 server and is one of the most sold and most rated plugins of Spigot so nowadays is common su see it in servers that use resourcepack_

https://user-images.githubusercontent.com/79306926/201423811-a4e4bf90-bdb1-489d-997a-79821d740978.mp4

### Configuration

```yaml
ItemsAdder_Support: <true/false> #to enable check or not of an ItemsAdder's block in BlockDamage 
```

### Payment (optional)

- [ ] I'm willing to pay for this feature

**Comment by CJCrafter** [comment]
https://itemsadder.devs.beer/developers/java-api/old-api
