### ISSUE TITLE
Weapon_Converter_Check currently not functioning

### ISSUE THREAD

**Issue by MelloJelloGames** [WeaponMechanics/MechanicsMain#211]
### Has this issue already been reported? Did you ask for help before making this report?

- [X] I have searched the existing issues
- [X] I have asked for help

### Current Behavior

      Weapon_Converter_Check:
      Type: <true/false>
      Name: <true/false>
      Lore: <true/false>
      Enchants: <true/false>
not being applied/activated in game

### Expected Behavior

Item converts to weapon if Weapon_Converter_Check conditions are correct on that item.

### Steps To Reproduce

1. Take the default AK-47 config
2. Add condition: Weapon_Converter_Check:
                             Type: true
3. Grab item in-game
Here's example config:
AK-47:
  Info:
    Weapon_Item:
      Type: "FEATHER"
      Name: "<gold>AK-47"
      Lore:
        - "<gray>Very reliable automatic assault rifle chambered in 7.62mm Soviet."
        - "<gray>Large caliber ammunition requires skill to control recoil."
        - ""
        - "<gray>Weapon Statistics <gold>-<gray> 66.5"
        - "<gold>➣<gray> 68 <gold>⟸ <gray>Accuracy"
        - "<gold>➣<gray> 76 <gold>⟸ <gray>Damage"
        - "<gold>➣<gray> 67 <gold>⟸ <gray>Range"
        - "<gold>➣<gray> 61 <gold>⟸ <gray>Fire Rate"
        - "<gold>➣<gray> 59 <gold>⟸ <gray>Mobility"
        - "<gold>➣<gray> 68 <gold>⟸ <gray>Control"
      Weapon_Converter_Check:
      type: true
(the rest is default AK.yml just leaving it out to save space)

### Frequency

100% of the time regardless of condition or item.

### Version and Log

https://gyazo.com/915fea5e34925d48c28ec4e4224f39d4
[logs_latest (1).log](https://github.com/WeaponMechanics/MechanicsMain/files/9993198/logs_latest.1.log)

**Comment by CJCrafter** [comment]
```
[11:42:28] [Server thread/INFO]: [WeaponMechanics] New serializer me.deecaad.weaponmechanics.weapon.reload.ammo.AmmoConverter will now override already added serializer me.deecaad.weaponmechanics.weapon.info.WeaponConverter
```
found it!
