### ISSUE TITLE
Options to allow scoping during firearm action.

### ISSUE THREAD

**Issue by DarkmanBree** [WeaponMechanics/MechanicsMain#218]
### Description

Currently while the firearm action is playing during like a sniper/shotgun rechamber, you either cannot scope in, or you are locked in scoping until the firearm action is done.

It would be nice to have the option for guns to be able to scope in/out while the firearm action is playing, because it really hinders with snipers/shotguns right now.

### Configuration

```yaml
Firearm_Action:
  Allow_Scoping: <true/false>
```

### Payment (optional)

- [ ] I'm willing to pay for this feature

**Comment by DeeCaaD** [comment]
Logically you should be able to scope in & out even while performing firearm actions / reload
