### ISSUE TITLE
WeaponMechanics Guns changes the CustomModelData of other non-related items

### ISSUE THREAD

**Issue by MomoLilya** [WeaponMechanics/MechanicsMain#219]
### Has this issue already been reported? Did you ask for help before making this report?

- [X] I have searched the existing issues
- [X] I have asked for help

### Current Behavior

Item with NBT tags changes CustomModelData when switching hands with a WeaponMechanics gun by pressing F

### Expected Behavior

CustomModelData that isn't part of the WeaponMechanics should not be affected by an offhand switch.

### Steps To Reproduce

1. Spawn an item with a CustomModelData of 0
2. Spawn a WeaponMechanics Gun
3. Place your gun on your offhand
4. Hold your item in your main hand
5. Press F

### Frequency

100% of the time.

### Version and Log

![2022-12-06_21 59 46](https://user-images.githubusercontent.com/54742840/206077468-555ce013-acc1-417a-8ad4-27077ee44ad6.png)
[latest.log](https://github.com/WeaponMechanics/MechanicsMain/files/10172408/latest.log)

**Comment by CJCrafter** [comment]
Duplicate of #221

**Comment by MomoLilya** [comment]
Pretty sure that's a duplicate of this

**Comment by CJCrafter** [comment]
> Pretty sure that's a duplicate of this

Yeah, but I keep whichever has more information
