### ISSUE TITLE
Don't start

### ISSUE THREAD

**Issue by Lerphie** [WeaponMechanics/MechanicsMain#22]
### Has this issue already been reported? Did you ask for help before making this report?

- [X] I have searched the existing issues
- [X] I have asked for help

### Current Behavior

.

### Expected Behavior

.

### Steps To Reproduce

.

### Frequency

.

### Version and Log

https://paste.gg/p/anonymous/6a4240d24f87490bb3f55f7561df84d7

### Anything else?

.

**Comment by DeeCaaD** [comment]
Updated the files, try redownloading

**Comment by Lerphie** [comment]
> Updated the files, try redownloading

Ye, it's work! Thanks!

**Comment by Lerphie** [comment]
These are the best guns I've seen. Will it be possible to put modifications on them?

**Comment by CJCrafter** [comment]
Please use [discord](https://discord.gg/ERVgpfg) if you want support quickly.

If by "modifications" you mean attachments, that will be available as an addon later. If you mean modifying/adding weapons, you can add anything you want to config (but you will have to model the guns).
