### ISSUE TITLE
Weird gun swap glitch

### ISSUE THREAD

**Issue by democracycraft** [WeaponMechanics/MechanicsMain#221]
### Has this issue already been reported? Did you ask for help before making this report?

- [X] I have searched the existing issues
- [X] I have asked for help

### Current Behavior

When you have a gun in your off hand and click f to switch it with your main have it gives the sword the texture of a gun. 

### Expected Behavior

It should keep the textures of the items seperate

### Steps To Reproduce

1. Hold a weapon
2. Hold a diamond sword or whatever vanilla material your gun is based off of
3. Press F to swap 

### Frequency

100% of the time when you do the steps to reproduce

### Version and Log

[06:16:14 INFO]: WeaponMechanics, v1.14.2
[06:16:14 INFO]:   ➢ Authors: DeeCaaD, CJCrafter
[06:16:14 INFO]:   ➢ Command: /weaponmechanics
[06:16:14 INFO]:   ➢ Server: Pufferfish git-Pufferfish-46 (MC: 1.19.2)
[06:16:14 INFO]:   ➢ MechanicsCore: 1.8.1
[06:16:14 INFO]:   ➢ Java: 17.0.2
[06:16:14 INFO]:   ➢ Supported plugins: WorldEdit, WorldGuard, PlaceholderAPI, ViaVersion

### Anything else?

https://user-images.githubusercontent.com/62296630/206637257-d93f9acf-9657-4495-8a12-495731a365d9.mp4

**Comment by democracycraft** [comment]
The sword has to be damaged or enchanted.

**Comment by CJCrafter** [comment]
Only happens when the item already has an `ItemMeta`, which is why this bug has been hidden for a long time. Caused by the dual wielding feature.
