### ISSUE TITLE
Made Delay_Between_Shot to global like old crackshot

### ISSUE THREAD

**Issue by legendwarz** [WeaponMechanics/MechanicsMain#223]
### Description

pls ,I have been wait for this since August. I rellay want Delay_Between_Shot to global like old crackshot

### Configuration

```yaml
none
```

### Payment (optional)

- [ ] I'm willing to pay for this feature

**Comment by CJCrafter** [comment]
Duplicate #148 

If you want a feature added quickly, offer to pay for it. Otherwise, we are too busy with college. Maybe after finals.
