### ISSUE TITLE
Repair Item Bug

### ISSUE THREAD

**Issue by 3Lord3** [WeaponMechanics/MechanicsMain#224]
### Has this issue already been reported? Did you ask for help before making this report?

- [X] I have searched the existing issues
- [X] I have asked for help

### Current Behavior

I used the default Repair config module on default AK-47. Repairing with repair Item doesn't work.
The repair item is set to one and nothing happens 

### Expected Behavior

When a repair item is used, the weapon is restored

### Steps To Reproduce

1. Use this weapon config
[AK-47.yml.txt](https://github.com/WeaponMechanics/MechanicsMain/files/10214383/AK-47.yml.txt)
2. Break the weapon
3. Repair it with red wool

### Frequency

It happens 100% of time

### Version and Log

[latest.log](https://github.com/WeaponMechanics/MechanicsMain/files/10214398/latest.log)
![image](https://user-images.githubusercontent.com/62335161/207228049-bb1c9fb5-954a-498c-a8f5-59c761f78d46.png)

### Anything else?

https://user-images.githubusercontent.com/62335161/207228559-a30ec8a9-95aa-4b15-b7a1-73109a0d72a6.mp4

**Comment by CJCrafter** [comment]
can confirm that this is a bug

**Comment by CJCrafter** [comment]
actually it was a misconfiguration. Added a check for this. 
```yaml
      Repair_Items:
        Item_1:
          Type: RED_WOOL
          Repair_Amount: 30
```
should have been
      Repair_Items:
        Item_1:
          Item: 
            Type: RED_WOOL
          Repair_Amount: 30

**Comment by CJCrafter** [comment]
^ I added that check to make sure users are forced to input an item
