### ISSUE TITLE
Can't reload weapon

### ISSUE THREAD

**Issue by XyBv587** [WeaponMechanics/MechanicsMain#225]
### Has this issue already been reported? Did you ask for help before making this report?

- [X] I have searched the existing issues
- [X] I have asked for help

### Current Behavior

Update WM to v1.14.3
Update WMC to v1.4.0

I get one gun and reload it , it fine
but i get two gun and reload it , i can't reload

### Expected Behavior

just reload ammo

### Steps To Reproduce

1. get two gun
2. get some ammo
3. reload

### Frequency

100%

### Version and Log

![image](https://user-images.githubusercontent.com/38648529/208659424-8cf35322-e436-493d-950b-429a7846ce45.png)
[cant_reload.txt](https://github.com/WeaponMechanics/MechanicsMain/files/10268109/cant_reload.txt)

**Comment by CJCrafter** [comment]
It probably has something to do with the update to ammo last night, will fix today
