### ISSUE TITLE
Full auto unsupported with trigger "Left_click"

### ISSUE THREAD

**Issue by Nightshade73** [WeaponMechanics/MechanicsMain#234]
### Has this issue already been reported? Did you ask for help before making this report?

- [X] I have searched the existing issues
- [X] I have asked for help

### Current Behavior

Video link: [https://youtu.be/6eXu2fvuUew](url)

Weapons do not operate while using Fully_Automatic_Shots_Per_Second with Trigger Left_click;
`  Shoot:
    Trigger:
      Main_Hand: "LEFT_CLICK"
      Off_Hand: "LEFT_CLICK"
    Projectile_Speed: 200
    Projectiles_Per_Shot: 1
    Fully_Automatic_Shots_Per_Second: 10
`
The module responsible for breaking the weapon functionality is 
`
    Fully_Automatic_Shots_Per_Second: 10
`

Weapons function properly when not using Full Auto, such as Delay_Between_Shots:
`
  Shoot:
    Trigger:
      Main_Hand: "LEFT_CLICK"
      Off_Hand: "LEFT_CLICK"
    Projectile_Speed: 200
    Projectiles_Per_Shot: 1
    Delay_Between_Shots: 1
`

### Expected Behavior

The weapon should accept the Left click trigger input while using  Fully_Automatic_Shots_Per_Second

### Steps To Reproduce

Change weapon to Fully_Automatic_Shots_Per_Second while using Left click trigger.

### Frequency

100% reocurrence

### Version and Log

[latest.log](https://github.com/WeaponMechanics/MechanicsMain/files/10335103/latest.log)

[2023-01-03-1.log.gz](https://github.com/WeaponMechanics/MechanicsMain/files/10335107/2023-01-03-1.log.gz)

![image](https://user-images.githubusercontent.com/23036913/210322307-0ae1e387-f73c-48e3-bad9-8b8e9f8cda78.png)

**Comment by DeeCaaD** [comment]
Working as intended. MC doesn't support checking whether player is left or right clicking. 

Full-auto partially works only with right-click because the interact packet is sent every 200ms.
