### ISSUE TITLE
Virtual Ammunition (DELETED)

### ISSUE THREAD

**Issue by Lerphie** [WeaponMechanics/MechanicsMain#240]
### Description

Hi! Your plugin is very good, the best weapon plugin. But it lacks 1 very important parameter "virtual cartridges", I explain. Many people want to create a Call of Duty or Counter Strike in minecraft, but how to implement it if only physical ammunition exists in WeaponMechanics? I suggest adding the following. Create virtual cartridges with such a maximum number of cartridge units. Then these cartridges (as with physical ones now) can be connected to weapons. I'm not the only one who offers this feature, just too lazy to explain it to many

### Configuration

Any

If necessary I can pay for this feature

### Payment (optional)

- [X] I'm willing to pay for this feature

**Comment by CJCrafter** [comment]
A lot of work is being done for WM right now, and I won't take a paid commission for a bit.

**Comment by Lerphie** [comment]
> A lot of work is being done for WM right now, and I won't take a paid commission for a bit.

Is the answer yes or no? ;)

**Comment by CJCrafter** [comment]
No for now, yes later

**Comment by Lerphie** [comment]
> No for now, yes later

Hi! I'm back and ready to pay for the job. Are you ready to take this order?
