### ISSUE TITLE
Endermen do not teleport away from WM projectiles.

### ISSUE THREAD

**Issue by DarkmanBree** [WeaponMechanics/MechanicsMain#242]
### Has this issue already been reported? Did you ask for help before making this report?

- [X] I have searched the existing issues
- [X] I have asked for help

### Current Behavior

It is normal vanilla behavior for an Enderman to teleport away to dodge an incoming snowball, arrow,...
But since WM's projectile code is completely custom, this does not happen.
Instead Endermen take damage like any other mob without teleporting.

### Expected Behavior

Endermen teleporting away without taking WM bullet damage.

### Steps To Reproduce

1. Use any gun
2. Shoot an Enderman

### Frequency

100% of the time

### Version and Log

Since this is more of an oversight instead of a bug in the custom projectile code, there are no errors to be seen.

**Comment by CJCrafter** [comment]
https://youtu.be/BicRbEigelM
