### ISSUE TITLE
flashbang keep doing damage block

### ISSUE THREAD

**Issue by aldigunawan-dev** [WeaponMechanics/MechanicsMain#243]
### Has this issue already been reported? Did you ask for help before making this report?

- [X] I have searched the existing issues
- [X] I have asked for help

### Current Behavior

Doesn't matter what I did, 
- reset the config
- put block damage section and select "CANCEL" as the default behaviour
- Delete the block damage section

it still does block damage
![2023-01-31_19 21 15](https://user-images.githubusercontent.com/78894332/215763200-6d9bd217-4893-43dc-961e-c2d27d03753c.png)

### Expected Behavior

It shouldn't do any block damage when exploded

### Steps To Reproduce

just install the plugins, and throw a flashbang

### Frequency

100% 

### Version and Log

![2023-01-31_19 45 20](https://user-images.githubusercontent.com/78894332/215763523-3273cc11-54e6-4860-bbde-89bf27fe05a0.png)

logs
https://mclo.gs/L9uiBEe#L4057

**Comment by CJCrafter** [comment]
![image](https://user-images.githubusercontent.com/43940682/215787806-6f813527-36f2-4a01-a473-2e9de640ad72.png)
always check logs, my friend. We can help you in discord if you send us your config.
