### ISSUE TITLE
A supplement to the mechanics

### ISSUE THREAD

**Issue by RollexGrief** [WeaponMechanics/MechanicsMain#250]
### Description

Checking the sighting status of mechanics (as in eye=true/false)

scope=**true/false**

For example:
@Source{offset= x x x, eye=true/false, scope=**true/false**}"

### Configuration

```
```

### Payment (optional)

- [ ] I'm willing to pay for this feature

**Comment by CJCrafter** [comment]
what does it do? Does it check if the targeted entity is scoping?

**Comment by RollexGrief** [comment]
> what does it do? Does it check if the targeted entity is scoping?
If shooter in scope - do this mechanic

**Comment by RollexGrief** [comment]
This parameter is needed for example for mechanics FakeItem, if we use it to make the shells, then when you aim the vector of the shell should change because the sight and the standard state different models

> what does it do? Does it check if the targeted entity is scoping?

**Comment by CJCrafter** [comment]
https://github.com/WeaponMechanics/MechanicsMain/wiki/SimpleConditions#scoping-condition
