### ISSUE TITLE
Soulbound

### ISSUE THREAD

**Issue by Cuaris94** [WeaponMechanics/MechanicsMain#251]
### Description

A boolean setting to enable/disable soulbound to a weapon. If true, the weapon will not be dropped after death. (Just like crackshot and crackshotplus do)

### Configuration

WeaponTest.yaml
Soulbound:
  Enabled: <true/false>
```


### Payment (optional)

- [ ] I'm willing to pay for this feature

**Comment by CJCrafter** [comment]
duplicate of #117
