### ISSUE TITLE
Improving conditions

### ISSUE THREAD

**Issue by RollexGrief** [WeaponMechanics/MechanicsMain#256]
### Description

New parameter **speed=?** for FakeItem condition

### Configuration

For Example:
```yaml
 - "FakeItem{type=music_disc_ward, customModelData=1, time=10, speed=1, velocity=RIGHT} @Source{offset=~1 1 1, eye=true}"
```

### Payment (optional)

- [ ] I'm willing to pay for this feature

**Comment by CJCrafter** [comment]
Already has it. 

try `velocity=~1 0 0` (Which is the same thing as `velocity=RIGHT`)
try `velocity~2 0 0` (Which is 2x speed of `velocity=RIGHT`)
