### ISSUE TITLE
Slowness in sight (DELETED)

### ISSUE THREAD

**Issue by Lerphie** [WeaponMechanics/MechanicsMain#263]
### Description

Add the ability to make the player slower (probably through mechanics or something similar, for example:

### Configuration

`
Slow_in_Zoom: <amount>`

### Payment (optional)

- [x] I'm willing to pay for this feature

**Comment by CJCrafter** [comment]
`Scope_Speed: 0%-100%`
100% = normal speed
50% = half speed
0% = no movement

It will be implemented using entity attributes. I will do this for $15.

Reminder for CJ to check "edge cases" for unscoping
* exceptions
* unscope after shoot (#73 and #257)
* player leaving the server

Fixes #233

**Comment by BananVovan34** [comment]
I'm waiting ))))

**Comment by CJCrafter** [comment]
Sorry I can't find any payment, can you send me your transaction ID (privately)? Make sure to always notify me.

**Comment by Lerphie** [comment]
> `Scope_Speed: 0%-100%` 100% = normal speed 50% = half speed 0% = no movement
> 
> It will be implemented using entity attributes. I will do this for $15.
> 
> Reminder for CJ to check "edge cases" for unscoping
> 
> * exceptions
> * unscope after shoot ([Weapon unscope when shot. #73](https://github.com/WeaponMechanics/MechanicsMain/issues/73) and [Removing the sight when fired from the awp #257](https://github.com/WeaponMechanics/MechanicsMain/issues/257))
> * player leaving the server
> 
> Fixes #233

Hi! I'm back and ready to pay for the job. Are you ready to take this order?

**Comment by CJCrafter** [comment]
Replaced with #265 

In the future, please do not open multiple issues for the same problem.
