### ISSUE TITLE
 The visual bug when changing slots is still there

### ISSUE THREAD

**Issue by Lerphie** [WeaponMechanics/MechanicsMain#265]
### Has this issue already been reported? Did you ask for help before making this report?

- [X] I have searched the existing issues
- [X] I have asked for help

### Current Behavior

The visual bug when changing slots is still there

### Expected Behavior

.

### Steps To Reproduce

.

### Frequency

.

### Version and Log

.

### Anything else?

.

**Comment by CJCrafter** [comment]
follow the format
