### ISSUE TITLE
Placeholders in lore

### ISSUE THREAD

**Issue by RollexGrief** [WeaponMechanics/MechanicsMain#267]
### Description

Working placeholders is item lore

### Configuration

```yaml
      Lore:
        - "&7Ammo: %ammo-type%"
        - "&7Weapon name: %weapon_title%"
```

### Payment (optional)

- [ ] I'm willing to pay for this feature

**Comment by CJCrafter** [comment]
https://github.com/WeaponMechanics/WeaponMechanicsCosmeticsWiki/issues/11
duplicate
