### ISSUE TITLE
Damage doesn't work

### ISSUE THREAD

**Issue by shady-sh** [WeaponMechanics/MechanicsMain#272]
### Current Behavior

I changed Base_Damage but doesn't work.

### Expected Behavior

maybe other minecraft tools are always the same.
if you set Weapon_Item.Type to STONE_SWORD, STONE_SPADE Etc...
The damage set to default tool's damage forcely.

### Steps To Reproduce

1. go to anyone gun file yml
2. change Weapon_Item.Type to STONE_SPADE, STONE_SWORD, DIAMOND_SWORD, DIAMOND_PICKAXE whatever tools
3. the damage set to default tool's damage forcely

### Version and Log

Version: 1.12.2 PaperBukkit

### Anything else?

please fix it i can't use gun

**Comment by CJCrafter** [comment]
join discord for support... Base_Damage is the amount of damage the projectiles deal, not the melee bash damage.

**Comment by shady-sh** [comment]
> 

Ok I think u didn't understand it.
the projectile damage have a same problem.

go to any Weapon Files and change weapon_item Type to STONE_SPADE
and then when you shoot, the projectile damage set to default tool's damage forcely
It means if Weapon_Item.Type is a stone, gold, diamond tool whatever the projectile damage doesn't work

k?
