### ISSUE TITLE
Burst doesn't work when Ticks_Between_Each_Shot is 0

### ISSUE THREAD

**Issue by DarkmanBree** [WeaponMechanics/MechanicsMain#281]
### Current Behavior

When `Ticks_Between_Each_Shot` is 0, Burst will no longer work in any way.

### Expected Behavior

The weapon should burst all shots in `Shots_Per_Burst` instantly when `Ticks_Between_Each_Shot` is 0.

### Steps To Reproduce

1. Use a weapon with Burst.
2. Set `Ticks_Between_Each_Shot` to 0.
3. Shoot, it will not burst, it'll either be Auto or Semi instead.

### Version and Log

![image](https://user-images.githubusercontent.com/29287160/229908182-261d315a-3816-4a04-b353-1214b9a9f2dd.png)
[latest.log](https://github.com/WeaponMechanics/MechanicsMain/files/11152627/latest.log)

### Anything else?

My AF2011A1 double barrel pistol is suffering.

**Comment by CJCrafter** [comment]
0 is not supported.
