### ISSUE TITLE
Spams Warnings About Creating Timings

### ISSUE THREAD

**Issue by FeyXieXzf** [WeaponMechanics/MechanicsMain#282]
### Current Behavior

The server is spamming tons of warnings shown below:
`[10:56:33 WARN]: Plugin 'WeaponMechanics' is creating timing 'Projectiles Runnable' - this is deprecated behavior, please report it to the authors: DeeCaaD, CJCrafter`

### Expected Behavior

Those warnings do not appear.

### Steps To Reproduce

1. Install latest 1.19.4 Purpur
2. Install this plugin
3. Start server

### Version and Log

Tested on a completely new server.

[latest.log](https://github.com/WeaponMechanics/MechanicsMain/files/11154819/latest.log)

Versions:
Minecraft: 1.19.4
Purpur: #1953
WeaponMechanics: 2.2.1
MechanicsCore: 2.2.3

### Anything else?

Configs of this plugin are not modified.

**Comment by DeeCaaD** [comment]
I think @CJCrafter already fixed this in some dev build, but didn't commit changes?

**Comment by FeyXieXzf** [comment]
I've just checked the code and seems that this _was_ n't a problem, however paper has deprecated timings recently, so the server starts spamming these warnings.
