### ISSUE TITLE
In Minecraft version 1.12.2, the plugin no longer opens. (v2.2.0-v2.2.5)

### ISSUE THREAD

**Issue by TeQTabanca** [WeaponMechanics/MechanicsMain#288]
### Current Behavior

The plugin became unusable after v1.9.4.

### Expected Behavior

The plugin should not give an error when opening.

### Steps To Reproduce

1- I download the current version and put it in the plugins folder.
2 I'm starting the server.

### Version and Log

Error: https://paste.gg/p/anonymous/a9a7318d356249229669aada9d7b8dde

Mc Version: 1.12.2-Spigot

**Comment by CJCrafter** [comment]
This is caused by the new String[] persistent data stored in items, which will be used for attachments. Class loading issues can be difficult, I think I'll need to abstract out the logic from the NBTCompatibility interface so nothing should get loaded... Will update this thread.
