### ISSUE TITLE
Battery packs

### ISSUE THREAD

**Issue by TrentrickLamar** [WeaponMechanics/MechanicsMain#295]
### Description

The idea I'd like to present is the implementation of an optional "battery pack" configuration for science fiction weapons. This feature would enhance the immersive experience and provide server owners with the ability to customize weapon mechanics further.

By default, the battery level would start at 100% and the depletion rate could be chosen by the server owner. This rate would determine how many projectiles can be fired before the battery depletes by 1%. For instance, setting the rate to 500 would require 500 rounds to be fired before losing 1% battery life.

When the battery is fully depleted, players would be required to craft a new battery pack to reload their weapon. This mechanism would not only make science fiction weapons more engaging and unique but also provide additional gameplay opportunities through crafting and resource management.

### Configuration

    Ammunition_Settings:
      Type: <AmmoType (bullet/battery)>
      Depletion_rate: <integer representing the number of bolts fired before depleting by 1% if using a battery>
        Consume_upon_reloading <yes/no (if the battery pack is consumed from your inventory upon reloading your weapon>

### Payment (optional)

- [ ] I'm willing to pay for this feature

**Comment by TrentrickLamar** [comment]
In reference to consume_upon_reloading:

This is contingent on the idea that it is possible to keep the battery pack in your inventory without having it fire anymore upon reaching a level of 0 unlike bullets which will disappear if you reach 0

**Comment by CJCrafter** [comment]
This is the same thing as a magazine. Stores x bullets, consume y bullets each shot. Already possible.
