### ISSUE TITLE
Double kills

### ISSUE THREAD

**Issue by Kleypex** [WeaponMechanics/MechanicsMain#296]
### Current Behavior

When you kill player it counts as 2 and adds 2 to statistics 

### Expected Behavior

Should only give 1 kill when you kill other player. Right now it gives 2

### Steps To Reproduce

Not needed

### Version and Log

Not needed

**Comment by CJCrafter** [comment]
Fixed in e709d32e0073ddd91b03e89b0e117af25c21e4f2
