### ISSUE TITLE
Whitelisted through blocks + Break block destroys projectiles

### ISSUE THREAD

**Issue by DarkmanBree** [WeaponMechanics/MechanicsMain#299]
### Current Behavior

If you combine the Projectile Through feature with WMC's break block feature, the block will break but the projectile will be destroyed, failing to go through it.

### Expected Behavior

The projectile should destroy the whitelisted block, but still go through without the projectile being destroyed.

### Steps To Reproduce

1. [Use this config.](https://pastebin.com/9SKVgvuY)
2. Shoot through glass panes, glass pane breaks and projectile disappears.
3. Shoot through normal glass, glass does not break, but projectile goes through fine.

### Version and Log

There are no console errors.

![image](https://user-images.githubusercontent.com/29287160/235906114-0a2f08a8-2e6c-4851-81dc-01cbe0b94083.png)

### Anything else?

This is only the case if you use **whitelisted blocks**.
If you use `Allow_Any`, then projectiles pass through blocks also being broken fine.

**Comment by CJCrafter** [comment]
I *think* this issue is caused because the block is broken before the projectile calculates through, which means that suddenly projectile is going through `AIR` (which is not on the list for Through, since of course it isn't!)

More testing required.

**Comment by CJCrafter** [comment]
Fixed in [77bd2ab](https://github.com/WeaponMechanics/MechanicsMain/commit/77bd2ab9c592c123fc7d1eb4533daec90ac7aa23)

**Comment by CJCrafter** [comment]
The fix has been improved as block ray tracing now returns the block state instead of x-y-z coordinates.
