### ISSUE TITLE
Error with installing plugin

### ISSUE THREAD

**Issue by TheDeshGame** [WeaponMechanics/MechanicsMain#300]
### Current Behavior

The plugin does not work on version 1.14.4 Spigot

### Expected Behavior

Plugin operation

### Steps To Reproduce

1. Start Server
2. Yeeees error!

### Version and Log

1.14.4 Spigot
Plugin version: WeaponMechanics-2.2.6, MechanicsCore-2.2.4, protocollib latest

Logs:
[logs.txt](https://github.com/WeaponMechanics/MechanicsMain/files/11414763/logs.txt)

**Comment by DeeCaaD** [comment]
Update to java 16 or newer
