### ISSUE TITLE
Sprint skin crouch

### ISSUE THREAD

**Issue by 3Lord3** [WeaponMechanics/MechanicsMain#301]
### Current Behavior

If you start crouch while running, the Sprint model will not be replaced by Default
If you start crouch while walking, the Sprint model does not appear

### Expected Behavior

If you start sneaking while running, the Sprint model will be replaced by the Default model

### Steps To Reproduce

1. Set the Default and Sprint skin
2. Run
3. While running, start sneaking

### Version and Log

![изображение](https://user-images.githubusercontent.com/62335161/237040123-ee4bde89-6890-4da1-9389-1ef748e9a58e.png)

### Anything else?

This seems to be normal behavior for the PlayerToggleSprintEvent

**Comment by CJCrafter** [comment]
This is normal behavior and expected. You are still sprinting; you are just crouched as well. When you uncrouch, you will continue sprinting. This works as intended.
