### ISSUE TITLE
Gun unload/empy magazine when you load

### ISSUE THREAD

**Issue by TeslaGM** [WeaponMechanics/MechanicsMain#31]
### Description

A way for unload the gun and give back ammo (maybe not the magazine full/or maybe just projectiles) and when you load a gun he gives you back the magazine empy

### Configuration

  Ammo:
    Give_ammo_back_when_you_unload: <true/false>
    Give_magazine: <true/false>
    Ammo_Item_ID: ITEM
    Ammo_Name_Check: "NAME"
    Give_empy_magazine_when_you_load_gun: : <true/false>

**Comment by DeeCaaD** [comment]
Do you mean like [Unload_Ammo_On_Reload](https://github.com/WeaponMechanics/MechanicsMain/wiki/Reloading#unload_ammo_on_reload-boolean)?

Fillable magazines was a plan at some point but were dropped out. I assume you meant this with giving back "empty magazines"

**Comment by DeeCaaD** [comment]
Merged with #41
