### ISSUE TITLE
A few bugs I found by turning on Debug in Version 1.12.2

### ISSUE THREAD

**Issue by TeQTabanca** [WeaponMechanics/MechanicsMain#313]
### Current Behavior

Every time I use the /wm reload command, TPS drops and the server lags for a few seconds.

### Expected Behavior

TPS should not drop every time I use the /wm reload command.

### Steps To Reproduce

1. Turn on debug in config.yml file and set debug level to 3
2. Restart the server for the debug feature to turn on
3. After WeaponMechanics or MechanicsCore plugin is opened on the server, it will give a lot of errors, or after the server is started, using the /wm reload command will give a lot of errors in the server console.

### Version and Log

```
[12:54:14 INFO]: WeaponMechanics, v2.2.10
[12:54:14 INFO]:   ➢ Authors: DeeCaaD, CJCrafter
[12:54:14 INFO]:   ➢ Command: /weaponmechanics
[12:54:14 INFO]:   ➢ Server: CraftBukkit git-Spigot-79a30d7-f4830a1 (MC: 1.12.2)
[12:54:14 INFO]:   ➢ MechanicsCore: 2.2.4
[12:54:14 INFO]:   ➢ Java: 17.0.7
[12:54:14 INFO]:   ➢ Supported plugins: No supported plugins installed
```

**MyhticMob bugs are excluded.**
https://paste.gg/p/anonymous/aeeb5221f8d3467eb5908b237d3960ea

### Anything else?

In general, every time I used the /wm reload command, TPS would not drop and there would be no server lag.

**Comment by CJCrafter** [comment]
Works as intended, debug mode spits out errors because some java classes are compiled to support older versions, some newer. Using `/wm reload` has to read, parse, and serialize every bit of config. Expect a lag spike always. 2.0.0 added more serializers, so that may be the increased lag you experience.

**Comment by CJCrafter** [comment]
To provide more context, those are errors **we know** are happening, and we specifically "catch" and handle them to make they don't cause any issues. We must go through this process to support 1.12 - 1.19.4.
