### ISSUE TITLE
Changes need to be made to make this plugin EULA-compliant.

### ISSUE THREAD

**Issue by bauerbach** [WeaponMechanics/MechanicsMain#317]
### Description

Mojang seems to be enforcing their RULA more aggressively now. Therefore, the guns should be retextured and renamed.

### Configuration

N/A

### Payment (optional)

- [ ] I'm willing to pay for this feature

**Comment by CJCrafter** [comment]
no.

**Comment by bauerbach** [comment]
Why not? This plugin is meant to be used on servers.
