### ISSUE TITLE
Itemsadder compatibility

### ISSUE THREAD

**Issue by Waliuss** [WeaponMechanics/MechanicsMain#319]
### Description

Add support for [itemsadder](https://www.spigotmc.org/resources/%E2%9C%A8itemsadder%E2%AD%90emotes-mobs-items-armors-hud-gui-emojis-blocks-wings-hats-liquids.73355/) please

### Configuration

Any

### Payment (optional)

- [ ] I'm willing to pay for this feature

**Comment by CJCrafter** [comment]
??
