### ISSUE TITLE
Minestom - support

### ISSUE THREAD

**Issue by Lerphie** [WeaponMechanics/MechanicsMain#323]
### Description

Hi, I need support for this server core. I know it doesn't have ProtocolLib support, but I'm willing to pay good money for it. 

https://github.com/hollow-cube/minestom-ce

### Configuration

.

### Payment (optional)

- [X] I'm willing to pay for this feature

**Comment by CJCrafter** [comment]
<img width="554" alt="image" src="https://github.com/WeaponMechanics/MechanicsMain/assets/43940682/dea9b7d3-e5cd-4d6b-9130-476a0c020243">

Best we can do is Folia at some point, which seems to have similar advantages

**Comment by Lerphie** [comment]
> Just to put it into perspective... We wrote WeaponMechanics now over the course of 4 years and is currently at 65,000 lines of code (But we've deleted 100,000+ lines of code in our various rewrites and optimizations).
> 
> We would have to do that AGAIN for Minestorm... So no.

Then support Folia? Can you add it?
