### ISSUE TITLE
Dupe on weapons

### ISSUE THREAD

**Issue by 4elovek1123** [WeaponMechanics/MechanicsMain#327]
### Current Behavior

If you take a weapon with the left mouse button and put it in the inventory when crafting, you can dupe the weapon.

### Expected Behavior

The weapon will move immediately to the free slot.

### Steps To Reproduce

1. Take the weapon in the left mouse button.
2. Open the inventory and put the weapons in the crafting cells.
3. Close the inventory and you get a lot of weapons.

### Version and Log

MechanicsCore-2.4.1
WeaponMechanics-2.5.1

**Comment by CJCrafter** [comment]
Can you send a video of this? I cannot replicate it.

**Comment by 4elovek1123** [comment]
https://github.com/WeaponMechanics/MechanicsMain/assets/104990916/3b21f701-fea6-40e7-8837-d62c8e774c9d

**Comment by CJCrafter** [comment]
https://github.com/WeaponMechanics/MechanicsMain/assets/43940682/af9be117-cb46-4af5-a8b9-6a1a7208294c

Seems like a crazy plugin incompatibility if anything 🤷

**Comment by CJCrafter** [comment]
I'm going to close this, since I cannot replicate the issue to any degree. Please re-open it if you are able to provide instructions on replicating the bug.
