### ISSUE TITLE
Weapon in off hand turns into a crossbow once you open the inventory while dual wielding

### ISSUE THREAD

**Issue by TomekHar** [WeaponMechanics/MechanicsMain#333]
### Current Behavior

The weapon in off hand turns into a crossbow the moment I open the inventory while having the weapon in off hand. Does not happen while holding 2 weapons at once.

### Expected Behavior

I expected the weapon not to turn into a crossbow.

### Steps To Reproduce

1. Dual wield weapons
2. Open the inventory

### Version and Log

[latest.log](https://github.com/WeaponMechanics/MechanicsMain/files/11918446/latest.log)

**Comment by CJCrafter** [comment]
Confirmed... Actually it seems like a mojang bug but 🤷

fixed in WMC 2.2.2
