### ISSUE TITLE
Can't have selective fire and dual wielding with different shoot triggers enabled

### ISSUE THREAD

**Issue by TomekHar** [WeaponMechanics/MechanicsMain#334]
### Current Behavior

Only having the same shoot trigger on both hands doesn't throw a config error. Having different triggers in main and off hand (ex. Main_Hand: "RIGHT_CLICK" Off_Hand: "LEFT_CLICK") throws a config error on plugin reload.

### Expected Behavior

I expected the plugin to accept the different shoot trigger.

### Steps To Reproduce

1. Use any config that features selective fire and different shoot triggers.
2. Reload the plugin.

### Version and Log

[latest.log](https://github.com/WeaponMechanics/MechanicsMain/files/11918506/latest.log)

**Comment by CJCrafter** [comment]
Hey @TomekHar,

the console actually says you are using full-auto. `LEFT_CLICK` does not work with full auto. I'll make the error message a bit more useful! Feel free to reopen the issue if you need to.
