### ISSUE TITLE
Oraxen support

### ISSUE THREAD

**Issue by TeslaGM** [WeaponMechanics/MechanicsMain#340]
### Description

Oraxen permits you to create custom armors without touching the original textures
So i was thinking, it would be amazing to have an actual support for Oraxen by this plugin

(Yea, ik that this suggestion is so bad written.. but.. i don't really know how to explain this thing..)

### Configuration

Oraxen:
   textures:
      - default/armors/X
   custom_model_data: []

### Payment (optional)

- [ ] I'm willing to pay for this feature

**Comment by CJCrafter** [comment]
huh? what am I adding/doing/changing?

**Comment by CJCrafter** [comment]
@TeslaGM ??
