### ISSUE TITLE
无法加载插件

### ISSUE THREAD

**Issue by Salukura** [WeaponMechanics/MechanicsMain#342]
### Current Behavior

我把压缩包里的两个插件放进了plugins文件夹，而且版本也是对的，但是进入游戏里就没办法使用，也没生成对应的文件夹

### Expected Behavior

尝试了很多次都这样

### Steps To Reproduce

1.解压压缩包
2.把两个插件放进plugins文件夹
3.启动服务器
4.进入游戏
5.输入/wm
6.无效

### Version and Log

[2023-07-24-2.log](https://github.com/WeaponMechanics/MechanicsMain/files/12142841/2023-07-24-2.log)

**Comment by AndyNoob** [comment]
Update your java version to 16 or up.

**Comment by DeeCaaD** [comment]
Use english
