### ISSUE TITLE
When the weapon hits the creature, an error is reported

### ISSUE THREAD

**Issue by starlightgl** [WeaponMechanics/MechanicsMain#343]
### Current Behavior

This is true for all weapons, and the weapon hits creatures without damage, and the plug-in has not touched any settings
![1OE{{ETCC 7(AJ W2DH6LNE](https://github.com/WeaponMechanics/MechanicsMain/assets/139604919/e003ea2f-5679-4ae9-9f86-2873575baae3)
The server version is 1.20 and the core is purpur

### Expected Behavior

He should not report errors and have harm

### Steps To Reproduce

1.Purpur core server
2.There is no moving plug-in configuration
3.Shoot at creatures with weapons

### Version and Log

[latest.log](https://github.com/WeaponMechanics/MechanicsMain/files/12249601/latest.log)

**Comment by CJCrafter** [comment]
![image](https://github.com/WeaponMechanics/MechanicsMain/assets/43940682/f96cda76-b57f-41b9-b43c-daad2c039ea8)
your server is out of date... this is a new method that we use. Update to latest. Not sure if Purpur has added it yet, but try updating it.
