### ISSUE TITLE
Crossbow uses stim's model

### ISSUE THREAD

**Issue by Quocnam201010** [WeaponMechanics/MechanicsMain#346]
### Current Behavior

Crossbow uses stim's model

### Expected Behavior

Crossbow uses vanilla model instead

### Steps To Reproduce

1. Join the server
2. Download the Resource Pack
3. Search Crossbow in inventory

### Version and Log

No need. It's resourcepack's problem

### Anything else?
![image](https://github.com/WeaponMechanics/MechanicsMain/assets/132324546/16af8575-9b8a-482f-bcaa-8f354d34ebcc)

_No response_

**Comment by TheFaik** [comment]
The same problem(  Author, fix this ...

**Comment by R411gun** [comment]
add the vanilla crossbow as a model next to the guns and set that to use with modeldata 0
I also encountered this issue (it's because of negative Modeldata)

**Comment by Quocnam201010** [comment]
A bit late.
Alternatively, you can change the stim model id to “-2” instead of “-1”
