### ISSUE TITLE
Worldguard protection stuff.

### ISSUE THREAD

**Issue by Terminator772** [WeaponMechanics/MechanicsMain#357]
### Current Behavior

Weapons are able to break blocks by default in protected regions that do not explicitly have the _**weapon-break-block**_ flag set to **_deny_**

### Expected Behavior

Weapons (in my opinion anyways) should not break blocks in protected regions unless the flag is explicitly set to true, additionally they should (apparently) obey standard build protection according to the worldguard discord.

### Steps To Reproduce

1. worldguard a region
2. fire an explosive or block-breaking gun
3. it destroys stuff
4. AHHHHHHHHHHHHHHHHHH

### Version and Log

weaponmechanics v2.6.5
paper 1.20.1-170

### Anything else?

![image](https://github.com/WeaponMechanics/MechanicsMain/assets/76029709/b5904546-678b-46d7-9724-ea3dcc313070)

**Comment by CJCrafter** [comment]
I know I suggested you open an issue for this, but I changed my mind and now disagree... People will think that the config isn't working and come to the discord for solving "their problem" when they just didn't setup world guard flags.
