### ISSUE TITLE
Weapon Packs

### ISSUE THREAD

**Issue by 5KFubi** [WeaponMechanics/MechanicsMain#361]
### Description

A special section on the discord server or on the spigotmc page for addons like weapon packs, skin packs, configs, either free or paid

### Configuration

I have no idea

### Payment (optional)

- [ ] I'm willing to pay for this feature

**Comment by CJCrafter** [comment]
you mean like...
![image](https://github.com/WeaponMechanics/MechanicsMain/assets/43940682/38549443-fae0-4bc9-bb47-c786327b0abc)
