### ISSUE TITLE
Invisible cartridge counter (PAY FEATURE)

### ISSUE THREAD

**Issue by Lerphie** [WeaponMechanics/MechanicsMain#362]
### Description

A parameter that stores invisible ammo in the "inventory" of Ammo_Inventory, as well as their maximum value of Max_Ammo_Inventory, which will be needed later. I suggest storing the values in the NBT date of the subject along the path PublicBukkitValues:{"weaponmechanics:ammo-inv-left": n, "weaponmechanics:max-ammo-inv": n} (the current number of ammo in the weapon is currently stored along the path of PublicBukkitValues:{"weaponmechanics:ammo-left": n}).

The logic of ammunition should be implemented as in Counter Strike.

If the value of Ammo_Inventory is set to -1, then the ammo in the "inventory" do not work. You also need to create Placeholder %ammo-inv-left%
Make the /wm ammo reload @player command, with which the NBT associated with ammo for all weapons in the player's inventory is updated from the config
Make the /wm ammo reload @player hotbar0-8/inventory0-26 command, with which the NBT associated with ammo for weapon in that slot is updated from the config

### Configuration

```yaml
gun:
 Reload:
  Magazine_Size: 7
  Ammo_Inventory: 35
  Max_Ammo_Inventory: 35
```

### Payment (optional)

- [X] I'm willing to pay for this feature

**Comment by CJCrafter** [comment]
Won't add, because how would this work with exp? Money?
++ super inefficient to implement and may even cause lag spikes on it's own.
