### ISSUE TITLE
WM shoot and hit mob will not trigger mythicmobs's ~onDamaged

### ISSUE THREAD

**Issue by iLunarCraft** [WeaponMechanics/MechanicsMain#367]
### Current Behavior

The damage mechanism of the new version of WM and WMC may be changed.
(**It has been tested that it is not a problem with mythicmobs**)
Version 2.X.X can normally trigger mythicmobs's ~onDamaged when hitting a monster. (just like it will make a sound when hit)
Still triggers normally when I attack with vanilla weapon.

### Expected Behavior

Can be triggered normally when using WM's gun when hit a monster.

### Steps To Reproduce

Shooting with WM guns to mythicmobs's mob

### Version and Log

WeaponMechanics-3.0.4
MechanicsCore-3.0.2
WeaponMechanicsCosmetics-3.0.0
No Error Log

**Comment by CJCrafter** [comment]
> Version 2.X.X can normally trigger mythicmobs's ~onDamaged when hitting a monster.
We have an issue in Discord that suggests it is a ModelEngine issue, and it works fine with vanilla mobs. Need video+latest.log file.

**Comment by iLunarCraft** [comment]
OK, thanks! The test monster is ModelEngine, that’s right. 
And the other monster i tested is a general armor stand.

**Comment by CJCrafter** [comment]
just bought modelengine, send me configs you want me to test

**Comment by iLunarCraft** [comment]
test_armor_stand:
  Type: Armor_Stand
  Display: "&2test_armor_stand"
  Health: 50
  Pose:
      Head: 0,0,0
  Options:    
    Interactable: false
    HasArms: false
    HasGravity: false    
  Skills:
  - sound{s=minecraft:block.anvil.land;p=0.9;v=0.2} @self ~onDamaged  
  - sound{s=minecraft:entity.iron_golem.repair;p=1.8;v=0.7} @self ~onDamaged  
   

Is mythicmobs configs.
This should be a good representation of the problem.
I can trigger the sound of taking damage when I attack with a vanilla weapon ,but not trigger when using WM.
This only happened in version 3.0

**Comment by CJCrafter** [comment]
Thanks, but does anybody have a ModelEngine config I can use? 

Apparently we have 2 different issues occurring with ModelEngine.

**Comment by CJCrafter** [comment]
Fixed in the MythicMobs dev builds

**Comment by iLunarCraft** [comment]
After setting Use_Vanilla_Damaging to on, trigger mythicmobs's ~onDamaged will work normally again.
I have only updated WM .
MM and it has been stuck in the past version for a long time.
It worked fine before updating WM
So I think it’s the damage system that comes with WM.
