### ISSUE TITLE
The Sprint skin doesn't work with items in the second hand

### ISSUE THREAD

**Issue by EmSockz** [WeaponMechanics/MechanicsMain#368]
### Current Behavior

The Sprint skin does not work when there is an item in the other hand.

https://github.com/WeaponMechanics/MechanicsMain/assets/67831957/1c1de937-d3ff-42be-a8a2-5c58fb476097

### Expected Behavior

The weapon skin should change regardless of the presence of the item in the second hand

### Steps To Reproduce

1 Get a weapon
2 Take the item in the other hand
3 Sprint

### Version and Log

![image](https://github.com/WeaponMechanics/MechanicsMain/assets/67831957/14fe0049-cbc7-4847-8b5e-e66c91c2adf1)
Also installed WMP and WMC plugins

**Comment by EmSockz** [comment]
The bug is still present in WeaponMechanics 3.1.0
![image](https://github.com/WeaponMechanics/MechanicsMain/assets/67831957/c0a80d15-9864-472e-91cf-5d88bb544d9b)

**Comment by CJCrafter** [comment]
Actually this works as intended.
```java
        if (triggerType != TriggerType.END_SPRINT
                && (entityWrapper.isSprinting() || triggerType == TriggerType.START_SPRINT)
                && !entityWrapper.isDualWielding()) {

            if (skins.hasAction(skin, SkinSelector.SkinAction.SPRINT))
                return SkinSelector.SkinAction.SPRINT;
        }
```
When you have 2 weapons, you don't want them to clip...

**Comment by CJCrafter** [comment]
I'll add an additional check for dual wielding to check if the other item is a weapon

**Comment by CJCrafter** [comment]
5f20869f0e3b4a398796c78d7d75e804a4fe7b19
fixed
