### ISSUE TITLE
Weapons Break "Unbreakable armor"

### ISSUE THREAD

**Issue by FunnyIvri** [WeaponMechanics/MechanicsMain#370]
### Current Behavior

when you shoot someone with "Unbreakable armor" (armor with Unbreakable:1) it still damages and destroys the armor.

### Expected Behavior

when you shoot someone with "Unbreakable armor" (armor with Unbreakable:1) it doesn't damage and destroy the armor.

### Steps To Reproduce

1. get a friend
2. get "Unbreakable armor" (armor with Unbreakable:1) 
3. use /data get entity {your username} Inventory to see the current armor damage and that it is actually unbreakable
4. have your friend shoot you.
5. use /data get entity {your username} Inventory to see the current armor damage and that it is actually unbreakable if the armor damage went up you did it! 

### Version and Log

version: 1.20.2
weapon_mechanics_core version: 3.0.6
weapon_mechanics version: 3.0.9
the log doesn't help in this bug.

**Comment by CJCrafter** [comment]
Sometimes I wish the Spigot API had methods for us to use. So many weird issues associated with armor. I'll add an unbreakable check.
