### ISSUE TITLE
Different display options for ammo_left

### ISSUE THREAD

**Issue by MatsCraft1** [WeaponMechanics/MechanicsMain#371]
### Description

It would be useful for the use of custom fonts using resource packs or other ways to display the ammo_left variable.
Instead of a simple number, it could show certain symbols or strings for different values.

Simple example:
5 ammo left -> IIIII
3 ammo left -> III
etc.

### Configuration

```
ammo_left_display:
  # If disabled it only uses numbers
  use_string: false/true
  ammo_amount:
  1: "I" # Put your special characters here.
  2: "II"
  3: "III"
  4: "IIII"
  5: "IIIII"
```
and so on

### Payment (optional)

- [x] I'm willing to pay for this feature

**Comment by CJCrafter** [comment]
Already implemented, just not released to public yet.
