### ISSUE TITLE
Sentinel/WeaponMechanics Compatibility

### ISSUE THREAD

**Issue by Ultrajungleboy** [WeaponMechanics/MechanicsMain#373]
### Description

Would be nice to have this feature brought back from CS as CSP isn't supported anymore on the new Minecraft versions.

### Configuration

NA

### Payment (optional)

- [X] I'm willing to pay for this feature

**Comment by CJCrafter** [comment]
**if** I add sentinels support, I will be doing it in full, and making super cool. That includes pathfinding to cover, making it usable for games, etc. I would be writing an entire AI logic and it would have to support all MC versions. ++There is no profit to be made, as people would expect it to be in the free version of the plugin. I cannot imagine myself starting such a large project for <$1000 right now. I am absurdly busy.

**Comment by CJCrafter** [comment]
MythicMobs is for you: https://cjcrafter.gitbook.io/weaponmechanics/addons#mythicmobs

**Comment by Ultrajungleboy** [comment]
I see what you're saying and I'm looking into using that as I can see specific use cases like bosses for that.  For what I'm looking for that doesnt fit the bill so I'll look at using QualityArmory or Crackshot with Citizens until I can get around to adding in compatibility myself

**Comment by tana-to** [comment]
@Ultrajungleboy did you manage to make wm compatible with sentinel ?
