### ISSUE TITLE
No projectiles/damage and no gui

### ISSUE THREAD

**Issue by Lorafen223** [WeaponMechanics/MechanicsMain#380]
### Current/Expected Behavior

When I'm equipping a pistol or AK for example, I get no gui and shoot, but no projectiles/no damage. My current server version is 1.20.4 latest purpur. Seems only Kar98k and AX_50 do damage, but still no gui. I tried making new clean server, still no luck. Using latest WeaponMechanics-3.1.9 and MechanicsCore-3.1.6.

### Steps To Reproduce

I had this problem in the older versions too, I don't know why It happens, I have this one server that this plugin works on.

### Log File

[latest.log](https://github.com/WeaponMechanics/MechanicsMain/files/13660802/latest.log)

**Comment by Lorafen223** [comment]
Here are logs from working server
[latest(of working).log](https://github.com/WeaponMechanics/MechanicsMain/files/13661125/latest.of.working.log)

**Comment by Lorafen223** [comment]
Update 
On spigot, It has gui, but no projectiles. It works as intended only on purpur-1.20.2-2094 for me.

**Comment by Lorafen223** [comment]
On spigot 1.20.4 from 5th december doesn't work for me too. Is it only me who has this problem?

**Comment by Lorafen223** [comment]
Update 
Using latest WeaponMechanics-3.1.10 and MechanicsCore-3.1.7 on spigot 1.20.4 from 5th december. It seems that all projectiles are working and doing damage, but still no gui/ammo count, here is latest log.
[latest.log](https://github.com/WeaponMechanics/MechanicsMain/files/13726789/latest.log)
Plugin is working great, looking forward to the next update. Will buy cosmetics in a few days, as soon as I get pay check.

**Comment by Lorafen223** [comment]
But also, It would be nice to be able to optionally disable gui/ammo count. Gameplay without knowing ammo count seems like a nice option too.

**Comment by CJCrafter** [comment]
Looks like you experienced #381's issue. That has been fixed.

As for your question, everything is configurable. I recommend checking out the wiki or asking in our discord for support.
