### ISSUE TITLE
Weapon with no projectile

### ISSUE THREAD

**Issue by tsutitire** [WeaponMechanics/MechanicsMain#381]
### Current/Expected Behavior

When I'm trying to use default AK-47 or other weapons, weapon make some sound and recoils but there were not any projectile or damage.
I tried all of them:
 re-install server and use only this plugin(with protocolib and mechanicscore)
 update or changing versions of  protocolib
 re-booting server and machine

There was no errors about gun propaties, or config.

 

### Steps To Reproduce

1) Install spigot server ver.1.20.2
2) install latest version of this plugin from spigot website
3) install latest version of protocolib from jenkins
  (the link of reccomended version is not working, so downloaded latest one and some versions, and they moved)
4) boot the server and try to shot

### Log File

[latest.log](https://github.com/WeaponMechanics/MechanicsMain/files/13749055/latest.log)

Each once I shot any weapon, there appears such log:
 [Server thread/ERROR]: Could not pass event PlayerInteractEvent to WeaponMechanics v3.1.10
・・・
Caused by: java.lang.NoSuchMethodError: 'net.minecraft.world.entity.Entity org.bukkit.craftbukkit.v1_20_R2.CraftWorld.createEntity(org.bukkit.Location, java.lang.Class)'

**Comment by CJCrafter** [comment]
A method name changed behind the scenes and I missed that. This was fixed 2 weeks ago here: 6a2ffea
