### ISSUE TITLE
weaponmechanicsplus change lore [WeaponEquipEvent] works

### ISSUE THREAD

**Issue by herojaecheol** [WeaponMechanics/MechanicsMain#390]
### Current/Expected Behavior

After applying weaponmechanicsplus
When changing lore to another plugin, [WeaponEquipEvent] is triggered.

### Steps To Reproduce

https://youtu.be/o8kRvr2khUs

### Log File

[latest.log](https://github.com/WeaponMechanics/MechanicsMain/files/14022828/latest.log)

**Comment by CJCrafter** [comment]
Works as intended
