### ISSUE TITLE
Problem with configuration

### ISSUE THREAD

**Issue by darknesscraft** [WeaponMechanics/MechanicsMain#394]
### Current/Expected Behavior

Hello guys,
could anyone tell me if there is any possibility to use items from another plugin like mythicmobs as ammo? or its MUST be created by weaponsmechanic plugin, by wm giveammo command?

is there any possibility to create weapons that will use ALL kind of STONE as ammo? with lore, without lore etc.?

### Steps To Reproduce

AK_47:
  Info:
    Weapon_Item:
      Type: "GOLDEN_HOE"
      Name: "<gold>AK 47"
    Ammo:
      Ammos:
        - AKAMMO

this work but its work only for ammo from weaponsmechanic plugin. Can this same be done for all kind of items with ID = 1?

### Log File

-

**Comment by CJCrafter** [comment]
Use discord for support, you already have a thread and asked this question... I'm not sure why you came here after I already answered your question.
