### ISSUE TITLE
I Found That setCancelled Cannot Be Used When Calling the WeaponEquipEvent Event Through the API

### ISSUE THREAD

**Issue by Kugana** [WeaponMechanics/MechanicsMain#398]
### Description

Can the method e.setCancelled(Boolean) be added to WeaponEquipEvent?
Because I have discovered that setting the item content in events related to WeaponShootEvent will trigger WeaponEquipEvent

### Configuration

```java
public void onequip(WeaponEquipEvent e){
  if(somthiing){
e.setCancelled(true);
return;
      }
  }
```

### Payment (optional)

- [ ] I'm willing to pay for this feature

**Comment by CJCrafter** [comment]
You can try to implement it! Good luck!

Sorry to sound rude... but it is **impossible** to add. You'll notice that WeaponEquipEvent works even when a dispenser equips the item into your hand. To understand why it is impossible, try to understand how we implemented the equipment event in the first place.
