### ISSUE TITLE
Explosion Regeneration

### ISSUE THREAD

**Issue by 3Lord3** [WeaponMechanics/MechanicsMain#402]
### Current/Expected Behavior

Despite Max_Blocks_Per_Update, explosions regenerate all blocks simultaneously with a long delay. Behavior is expected in accordance with the config

### Steps To Reproduce

1. Set Regeneration module in some explosive weapon
Regeneration:
      Ticks_Before_Start: 200
      Max_Blocks_Per_Update: 4 
      Ticks_Between_Updates: 1
2. Shoot

### Log File

[latest.log](https://github.com/WeaponMechanics/MechanicsMain/files/14669890/latest.log)

### Anything else?

[Discord thread](https://discord.com/channels/306158221473742848/1217870855007244349)
Weapon config:
[RPS_6.zip](https://github.com/WeaponMechanics/MechanicsMain/files/14669944/RPS_6.zip)

**Comment by CJCrafter** [comment]
I've followed your steps, and I cannot replicate. @3Lord3

**Comment by CJCrafter** [comment]
I believe that you are experiencing a conflicting plugin
