### ISSUE TITLE
The plugin changes the model data of the item held when our inventory is full and a weapon must come there when closing inventory

### ISSUE THREAD

**Issue by HC-Emro** [WeaponMechanics/MechanicsMain#403]
### Current/Expected Behavior

It should not change the model data of the item held when closing the full inventory.

### Steps To Reproduce

This bug occurs when we fill our inventory, hold an item in our hand and an weaponmechanic weapon on the cursor. When closing the inventory, the model data of the item held in the hand transforms to the model data of the weapon in the cursor. A video attached to show you.

### Log File

No errors in console : https://paste.gg/p/anonymous/0bb656f58dd84432b5fb19695abfb33c

### Anything else?

https://github.com/WeaponMechanics/MechanicsMain/assets/56135028/718a3821-b6a1-408b-8ab6-32c20cd64e14

**Comment by HC-Emro** [comment]
I also want to add that on the video the player have 8 glass panes on the second line, so its inventory is full.

**Comment by CJCrafter** [comment]
Cannot replicate. Likely a conflicting plugin.
