### ISSUE TITLE
Mechanics for specific deny shoot reasons

### ISSUE THREAD

**Issue by Terminator772** [WeaponMechanics/MechanicsMain#412]
### Description

As title states, Adding the ability to have specific mechanics for specific reasons a player can't shoot, such as a specific message and sound cue for trying to dual-wield rifles and a different message for trying to shoot while underwater.

### Configuration

I dunno

### Payment (optional)

- [ ] I'm willing to pay for this feature

**Comment by CJCrafter** [comment]
Use `<deny_reason>` variable in the `Deny_Mechanics`
