### ISSUE TITLE
Per weapon get permission

### ISSUE THREAD

**Issue by BugabuseMe** [WeaponMechanics/MechanicsMain#413]
### Description

Could you add a per weapon permission to get, like /wm get gunname and the permission being weaponmechanics.commands.get.gunname or that they need the use permission to get it?

### Configuration

```yaml
weaponmechanics.commands.get.gunname
weaponmechanics.commands.get.*
```

### Payment (optional)

- [ ] I'm willing to pay for this feature

**Comment by CJCrafter** [comment]
why?

**Comment by CJCrafter** [comment]
Won't add this because `/wm` is meant to be an admin command.
