### ISSUE TITLE
Differences in recoil for adjusting the FOV effect

### ISSUE THREAD

**Issue by Backas03** [WeaponMechanics/MechanicsMain#422]
### Description

In scope parts using a spyglass, the recoil changes by adjusting the POV effect.
When set to 0% there is almost no recoil.

Is there any other way to solve this issue?

No recoil control:
https://github.com/WeaponMechanics/MechanicsMain/assets/71801733/85e2647d-73a4-4a86-9f52-0bb9d095338a

With recoil control:
https://github.com/WeaponMechanics/MechanicsMain/assets/71801733/ded74d86-6cc6-42c5-8a64-454a9cda47fd

### Configuration

x

**Comment by CJCrafter** [comment]
Well.... if you disable zooming on the client side, how do you expect us to zoom in :thinking: 

Unfortunately, you just need to keep this setting on... no workaround.
