### ISSUE TITLE
/wm list and get/give do not work

### ISSUE THREAD

**Issue by mei1012** [WeaponMechanics/MechanicsMain#427]
### Current/Expected Behavior

1. Run command
2. Works

### Steps To Reproduce

1. Run commmand
2. Console error

### Log File

[https://mcpaste.io/7c4c4193b185b39b](https://mcpaste.io/7c4c4193b185b39b)

### Anything else?

Other commands seem to work fine.

https://github.com/WeaponMechanics/MechanicsMain/assets/77690808/e46bcbc4-c5a7-4230-a18c-7bae818927e3

**Comment by CJCrafter** [comment]
This was related to 1.20.6 changes. Now fixed.
