### ISSUE TITLE
Inventory Control on Weapons

### ISSUE THREAD

**Issue by karldros** [WeaponMechanics/MechanicsMain#429]
### Description

Can you add the ability to set a limit on each weapon usable on hotbar? this to prevent spaming the same weapons over again. For example only 1 bazooka is allowed to be equiped/use on a hotbar. This feature was also available on Crackshot before it was inactive. Thanks 

### Configuration

#You can create as many groups as you want. Messages and sounds are optional.
#Enforce these limits using the Inventory_Control node in the weapon's Item_Information module.
#The example below is used for the default weapon Bazooka.
Inventory_Control:
    Group_Bazookas:
        Limit: 1
        Message_Exceeded: "&e[IC] &bYou cannot have more than one Bazooka in the hot bar!"
        Sounds_Exceeded: LAVA_POP-1-1-0

### Payment (optional)

- [ ] I'm willing to pay for this feature

**Comment by CJCrafter** [comment]
Nope! I've explained this in a bunch of other places, but the TL:DR is that the system isn't good and results in buggy behavior.
