### ISSUE TITLE
Delays between aiming and switching guns.

### ISSUE THREAD

**Issue by DarkmanBree** [WeaponMechanics/MechanicsMain#43]
### Description

So basically I'm asking for a configurable delay per gun when you switch to a gun in your hotbar and one when you scope in/out.
Like, heavier weapons could take longer to equip when switching to them and also take longer to aim in or out.

During the delay, the weapon cannot be fired, however reloading should be still allowed, and unscoping during the scope delay should also be allowed so you shouldn't have to wait too long if you accidently aim for example.

### Configuration

```yaml
Scope:
  Firing_Delay_When_Scoping: <integer> (Should support decimals)
Info:
  Firing_Delay_When_Equipping: <integer> (Should support decimals)
```

**Comment by DeeCaaD** [comment]
Added
https://github.com/WeaponMechanics/MechanicsMain/releases/tag/v1.4.3
