### ISSUE TITLE
Out of ammo skin

### ISSUE THREAD

**Issue by outofthetime** [WeaponMechanics/MechanicsMain#44]
### Description

A skin for a gun when it has no ammo left (0 ammo in inventory or it says 0 in its ammo amt).

### Configuration

  Skin:
    Out_Of_Ammo_Inv: #for when there is no ammo in the inventory
    Out_Of_Ammo_Gun: #for when there it says 0 in its ammo amt

**Comment by CJCrafter** [comment]
When scoping, should scope skin or out of ammo skin be used?

**Comment by DeeCaaD** [comment]
I'd say that no ammo skin is prioritized? Meaning skins would be defined in this order:
```No ammo -> Scope_ -> Scope -> Reload -> Sprint -> Default```

**Comment by ethanviii** [comment]
there could be a no ammo scope skin too

**Comment by ethanviii** [comment]
along with that, scoping could be disabled when it has no ammo

**Comment by CJCrafter** [comment]
Adding in 1.5.6
