### ISSUE TITLE
I use Paper 1.16.5

### ISSUE THREAD

**Issue by GOSTE1** [WeaponMechanics/MechanicsMain#442]
### Current/Expected Behavior

There are a lot of errors in the console. I don't understand it, but I don't like it, so I want to get support.

### Steps To Reproduce

1. Start server
2. Seen error

### Log File

[latest.log](https://github.com/user-attachments/files/16602123/latest.log) last log file.

**Comment by CJCrafter** [comment]
Use Java 16, and join discord for support :+1:
