### ISSUE TITLE
Failing to set Lore to a weapon in the configuration file will cause the weapon to not load properly.

### ISSUE THREAD

**Issue by Ghost067** [WeaponMechanics/MechanicsMain#459]
### Current/Expected Behavior

As the title describes, the WM version I'm using is 3.4.12.

### Steps To Reproduce

Removing any weapon that loads properly and contains a Lore will not load properly.

### Log File

There are no errors reported in the logs.

**Comment by CJCrafter** [comment]
Closed for not following issue format. Use the discord for support.
