### ISSUE TITLE
Implement getDrops() on WeaponKillEntityEvent

### ISSUE THREAD

**Issue by rageyh** [WeaponMechanics/MechanicsMain#463]
### Description

Hi, I saw that the getDrops() method is missing in the WeaponKillEntityEvent. I would like it to be implemented so when an entity dies I can cancel the item drop. Thank you very much 

### Configuration

---

### Payment (optional)

- [ ] I'm willing to pay for this feature

**Comment by CJCrafter** [comment]
We aren't missing anything, it isn't something that is reasonably possible to implement there. You should listen to the EntityDeathEvent to cancel drops.
