### ISSUE TITLE
Weapons do 0 damage

### ISSUE THREAD

**Issue by Jynny35** [WeaponMechanics/MechanicsMain#473]
### Current/Expected Behavior

Weapons deal 0 damage against all entities.
Plugins are all up-to-date.

### Steps To Reproduce

No steps it just started happening soon after the most recent updates.
No conflicting plugins.

### Log File

[logs.zip](https://github.com/user-attachments/files/17372824/logs.zip)

### Anything else?

Thanks for your interest!

**Comment by jdmmc** [comment]
I reproduced the same problem. The solution is to set the damage as a float instead of an integer value.
![image](https://github.com/user-attachments/assets/f8fe3176-062e-4a77-b391-26d10e2c8d84)

**Comment by CJCrafter** [comment]
This has been fixed for while... make sure to use latest
