### ISSUE TITLE
Swap Hands reload doesn't work

### ISSUE THREAD

**Issue by Clawsssme** [WeaponMechanics/MechanicsMain#475]
### Current/Expected Behavior

So basically, reload perfectly works when you use Drop item for reload, but do not work when you use Swap hands as a reload button, it just starts reloading and stops at the last millisecond and cancels the reloading. I guess that fixing #462 is the reason

### Steps To Reproduce

Use Swap_hands as reload button

### Log File

No errors

### Anything else?

Sorry for my mistakes in grammar if there is some, not fluent in english

**Comment by R411gun** [comment]
Did some research on that, it is actually because of some Folia patches in 3.5.0

Here's the changelog between 3.4.14 and 3.5.0
(https://github.com/WeaponMechanics/MechanicsMain/compare/v3.4.14...v3.5.0)

SWAP_HANDS trigger is working fine in 3.4.14, just tested that

**Comment by R411gun** [comment]
awesome, thanks!

**Comment by Greensxfl** [comment]
v3.5.4, it still can't work at 1.21.1

**Comment by Greensxfl** [comment]
v3.5.4, it still can't work, just starts reloading and stops at the last millisecond and cancels the reloading

**Comment by R411gun** [comment]
gonna test this real quick
