### ISSUE TITLE
Weapon Attachment Sync Issue: Local Player vs. Other Players

### ISSUE THREAD

**Issue by rageyh** [WeaponMechanics/MechanicsMain#482]
### Current/Expected Behavior

Hello, I’ve a visual problem:

When I go to insert an attachment, the plugin updates the weapon only for the player holding them, other players,  who see the weapon in the hand of another (with cosmetic),  see them without attachments since only the item feather and not the item crossbow is updated

### Steps To Reproduce

1. get a weapon
2. attach an accessory to a weapon
3. see the weapon with another user

### Log File

[latest.log](https://github.com/user-attachments/files/18114291/latest.log)
https://paste.gg/p/anonymous/3dec9dd83ad54ae58a34a5926e6d1049

**Comment by CJCrafter** [comment]
Hey, this is a resource pack issue.

It happens when you use the crossbow feature, but forget to update the crossbow.json. Please join discord for support.

**Comment by rageyh** [comment]
> Hey, this is a resource pack issue.
> 
> 
> 
> It happens when you use the crossbow feature, but forget to update the crossbow.json. Please join discord for support. 

I used the crossbow feature to see weapons better in my hand, but if by enabling it external players cannot see my attachments in my hand, I will deactivate it. I thought it was a plugin problem that didn't update the item in hand
