### ISSUE TITLE
Shooting mobs with guns does not count as a player attack, so animals will not run around, and zombie piglins will not becom hostile

### ISSUE THREAD

**Issue by BookWyrm114** [WeaponMechanics/MechanicsMain#49]
### Has this issue already been reported? Did you ask for help before making this report?

- [X] I have searched the existing issues
- [X] I have asked for help

### Current Behavior

Shooting mobs with guns does not count as a player attack, so animals will not run around, and zombie piglins will not becom hostile

### Expected Behavior

For guns to properly affect mobs

### Steps To Reproduce

shoot zombie piglins and animals in survival

### Frequency

100%

### Version and Log

![image](https://user-images.githubusercontent.com/79489385/155898908-5f71af82-e743-47b4-b19f-976edcc4785f.png)
No issues in server log

**Comment by DeeCaaD** [comment]
Thanks for reporting! We didn't think of this so I assume this has something to do with our custom damaging system.

We will take a look into it and find a fix!
