### ISSUE TITLE
Add command /wm give <gun> <ammo amount>

### ISSUE THREAD

**Issue by EmSockz** [WeaponMechanics/MechanicsMain#60]
### Description

Add the command /wm give <gun> <amount ammo> To give a weapon with the specified amount of ammo, this is a minor command and may seem like a need for it at all. But she has a use in some shops with weapons and so on. Further.

### Configuration

```yaml
None
```

**Comment by CJCrafter** [comment]
Releasing a jar file in <30 minutes

Use `/wm give @p AK 1 {ammo:5}` for 5 ammo. Tab completions will help you get there.
