### ISSUE TITLE
Model when shooting

### ISSUE THREAD

**Issue by sdmaxINC** [WeaponMechanics/MechanicsMain#64]
### Description

Add the ability to change the weapon model when the player shoots. (I don't know why it doesn't include spaces and tabs in the configuration Description) 

### Configuration

Skin:
       Shoot:
      Type: <Material>
      Legacy_Data: <Integer>
      Custom_Model_Data: <Integer>
      Durability: <Integer>

**Comment by DeeCaaD** [comment]
This would cause model bobbing, so we wont add this. Sorry
