### ISSUE TITLE
Light on fire

### ISSUE THREAD

**Issue by sdmaxINC** [WeaponMechanics/MechanicsMain#65]
### Description

Used to create a temporary light when someone is firing the configured weapon for more realism.

### Configuration

    
light-on-fire:
      enabled: <true/false>
      light-level: <light level> (ex. 12)
      offset:
        x: <x offset> (ex. 1.0)
        y: <y offset> (ex 1.0)
        z: <z offset> (ex 1.0)
        multiplier: <multiplier> (ex 1.0)
      remove-delay: <delay in ticks> (ex. 20)

**Comment by DeeCaaD** [comment]
Will be in WMC

**Comment by CJCrafter** [comment]
Lighting is super taxing on the CPU, so to avoid that, I am going to do some fancy dynamic lighting stuff and only allow
```yaml
Muzzle_Flash: <true/false> # no other settings
```

**Comment by CJCrafter** [comment]
https://www.spigotmc.org/resources/104539/
