### ISSUE TITLE
Spread Reset Customization

### ISSUE THREAD

**Issue by marijay1** [WeaponMechanics/MechanicsMain#66]
### Description

The time it takes in-between bursts of a weapon to reset the spread.

### Configuration

yaml

Spread:
  Spread_Reset_Time: <double/int> 

Ticks or milliseconds is fine

**Comment by DeeCaaD** [comment]
Added
https://github.com/WeaponMechanics/MechanicsMain/commit/b027d541e78736f841da864f4b0473918f364b17
