### ISSUE TITLE
Magazine ammo amount consumed per shot.

### ISSUE THREAD

**Issue by DarkmanBree** [WeaponMechanics/MechanicsMain#71]
### Description

So, this should be simple.
This will control how many bullets are consumed from the magazine every shot, this will NOT affect how many bullets are fired from the gun, just how much ammo is consumed from the magazine.

This is needed for special guns with a hyperburst like the AN-94, G11K2 or guns that fire from two barrels like the AF2011A1.

### Configuration

```
  Shoot:
    Ammo_Consumed_Per_Shot: <amount>
```

**Comment by CJCrafter** [comment]
Shoot.Ammo_Per_Shot
