### ISSUE TITLE
Resource Pack Improvements

### ISSUE THREAD

**Issue by CJCrafter** [WeaponMechanics/MechanicsMain#78]
### Has this issue already been reported? Did you ask for help before making this report?

- [X] I have searched the existing issues
- [X] I have asked for help

### Current Behavior

1. Models block screen, making them feel clunky.
2. Top part of crosshair blocks iron-sights
3. Feathers are guns

### Expected Behavior

1. When aiming, the default models block the screen, denying bullet hit feedback. Raise iron sights
2. The top crosshair blocks the iron-sights of default guns. We should remove top bit
3. Items missing textures should have vanilla item models
  * Airstrike -> REDSTONE_TORCH
  * Grenade -> RED_CANDLE
  * STIM -> LIGHTNING_ROD
  * Flashbang -> BLACK_CANDLE
  * Semtex -> TNT

### Steps To Reproduce

1. /wm get <weapon>
2. scope in

### Frequency

100%

### Version and Log

n/a

**Comment by DeeCaaD** [comment]
Will take a look into this when I get to it.  

I might convert default weapons to use the `attack speed` and Ill also consider modifying the item bob fix so that it doesn't occur with such weapons (since it isn't then required) #68

**Comment by DeeCaaD** [comment]
https://github.com/WeaponMechanics/MechanicsMain/commit/6d7699d20cbea0e8cc5426901157e98e13a31f58
