### ISSUE TITLE
Placeholders everywhere

### ISSUE THREAD

**Issue by RollexGrief** [WeaponMechanics/MechanicsMain#81]
### Description

Ability to use placeholders weaponmechanics in other plugins via placeholderapi. For example, if you display a message from another plugin using placeholder %weapon-title% and at this point the player is holding a weapon then the placeholder will be the name of the weapon, if the weapon is not holding nothing will be displayed well or will be displayed that is specified in the configuration.

### Configuration

```yaml
```

**Comment by DeeCaaD** [comment]
Duplicate request

https://github.com/WeaponMechanics/MechanicsMain/issues/58

**Comment by RollexGrief** [comment]
Thans for replay ! You best and good luck )
