### ISSUE TITLE
Fix enchantments usage

### ISSUE THREAD

**Issue by DeeCaaD** [WeaponMechanics/MechanicsMain#89]
### Has this issue already been reported? Did you ask for help before making this report?

- [X] I have searched the existing issues
- [X] I have asked for help

### Current Behavior

Enchantments get key doesn't work as intended with damaging

### Expected Behavior

Enchantment checks work properly

### Steps To Reproduce

.

### Frequency

100%

### Version and Log

-

**Comment by CJCrafter** [comment]
Fixed in fabad2b
