### ISSUE TITLE
Weapon up & down

### ISSUE THREAD

**Issue by DeeCaaD** [WeaponMechanics/MechanicsMain#9]
**Expected Behavior**
Weapon wouldn't go up and down

**Observed Behavior**
Weapon going up and down when shooting

**Steps to Reproduce**
Take any weapon and shoot

**Frequency**
When the weapon item stack is updated

**Version**
Happened also in 1.17
![kuva](https://user-images.githubusercontent.com/18332343/146780664-6a79f71c-275b-43de-9504-27c29c4aa282.png)

**Additional context**
-

**Comment by DeeCaaD** [comment]
Probably has something to do with EntityEquipmentEvent not working in newer versions

**Comment by CJCrafter** [comment]
Some things we know
* A gun bobs whenever you unequip it, then equip it.
* When a gun is bobbing, press your 'drop' key to stop the bobbing
  * The gun *should* never bob until you unequip it.
* When the gun is not bobbing, pressing the 'drop' key causes the item to visually disappear
  * This is separate from actually disappearing though
  * The gun is still in the inventory, and can be seen after re-equipping it.

**Comment by CJCrafter** [comment]
Mostly fixed, but:
* Gun will not change skin (scope -> normal)
* Unconfirmed if dangerous item deletion error was fixed
